export enum ChargingSessionStatus {
    PENDING = 'PENDING',
    ACTIVE = 'ACTIVE',
    COMPLETED = 'COMPLETED',
    INTERRUPTED = 'INTERRUPTED',
    CANCELLED = 'CANCELLED',
    AUTO_CANCELLED = 'AUTO_CANCELLED',
}
