export enum OrderStatus {
    CREATED = 'CREATED',
    PENDING = 'PENDING',
    CONFIRMED = 'CONFIRMED',
    INPROGRESS = 'INPROGRESS',
    PARTIALLYFULFILLED = 'PARTIALLYFULFILLED',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
    REJECTED = 'REJECTED',
    FAILED = 'FAILED',
    RETURNED = 'RETURNED',
    REFUNDED = 'REFUNDED',
    ONHOLD = 'ONHOLD',
}
