export enum BecknPaymentStatus {
    INITIATED = "INITIATED",
    PENDING = "PENDING",
    AUTHORIZED = "AUTHORIZED",
    CAPTURED = "CAPTURED",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    CANCELLED = "CANCELLED",
    REFUNDED = "REFUNDED",
    PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED",
    CHARGEBACK = "CHARGEBACK",
    DISPUTED = "DISPUTED",
    EXPIRED = "EXPIRED",
    REVERSED = "REVERSED",
    VOIDED = "VOIDED",
    SETTLED = "SETTLED",
    ON_HOLD = "ON_HOLD",
    ADJUSTED = "ADJUSTED"
}
