// 8.4.3
export enum OCPICapability {
    CHARGING_PROFILE_CAPABLE = 'CHARGING_PROFILE_CAPABLE',
    CHARGING_PREFERENCES_CAPABLE = 'CHARGING_PREFERENCES_CAPABLE',
    CHIP_CARD_SUPPORT = 'CHIP_CARD_SUPPORT',
    CONTACTLESS_CARD_SUPPORT = 'CONTACTLESS_CARD_SUPPORT',
    CREDIT_CARD_PAYABLE = 'CREDIT_CARD_PAYABLE',
    DEBIT_CARD_PAYABLE = 'DEBIT_CARD_PAYABLE',
    PED_TERMINAL = 'PED_TERMINAL',
    REMOTE_START_STOP_CAPABLE = 'REMOTE_START_STOP_CAPABLE',
    RESERVABLE = 'RESERVABLE',
    RFID_READER = 'RFID_READER',
    START_SESSION_CONNECTOR_REQUIRED = 'START_SESSION_CONNECTOR_REQUIRED',
    TOKEN_GROUP_CAPABLE = 'TOKEN_GROUP_CAPABLE',
    UNLOCK_CAPABLE = 'UNLOCK_CAPABLE',
}

// #OCPIv2.1.1 
// 8.4.3
export enum OCPIv211Capability {
    CHARGING_PROFILE_CAPABLE = 'CHARGING_PROFILE_CAPABLE',
    CREDIT_CARD_PAYABLE = 'CREDIT_CARD_PAYABLE',
    REMOTE_START_STOP_CAPABLE = 'REMOTE_START_STOP_CAPABLE',
    RESERVABLE = 'RESERVABLE',
    RFID_READER = 'RFID_READER',
    UNLOCK_CAPABLE = 'UNLOCK_CAPABLE',
}

// 8.4.4
export enum OCPIConnectorFormat {
    SOCKET = 'SOCKET',
    CABLE = 'CABLE',
}

// 8.4.5
export enum OCPIConnectorType {
    CHADEMO = 'CHADEMO',
    CHAOJI = 'CHAOJI',
    DOMESTIC_A = 'DOMESTIC_A',
    DOMESTIC_B = 'DOMESTIC_B',
    DOMESTIC_C = 'DOMESTIC_C',
    DOMESTIC_D = 'DOMESTIC_D',
    DOMESTIC_E = 'DOMESTIC_E',
    DOMESTIC_F = 'DOMESTIC_F',
    DOMESTIC_G = 'DOMESTIC_G',
    DOMESTIC_H = 'DOMESTIC_H',
    DOMESTIC_I = 'DOMESTIC_I',
    DOMESTIC_J = 'DOMESTIC_J',
    DOMESTIC_K = 'DOMESTIC_K',
    DOMESTIC_L = 'DOMESTIC_L',
    DOMESTIC_M = 'DOMESTIC_M',
    DOMESTIC_N = 'DOMESTIC_N',
    DOMESTIC_O = 'DOMESTIC_O',
    GBT_AC = 'GBT_AC',
    GBT_DC = 'GBT_DC',
    GB_T_20234_T3 = 'GB_T_20234_T3', // Added for some CPOs
    IEC_60309_2_single_16 = 'IEC_60309_2_single_16',
    IEC_60309_2_three_16 = 'IEC_60309_2_three_16',
    IEC_60309_2_three_32 = 'IEC_60309_2_three_32',
    IEC_60309_2_three_64 = 'IEC_60309_2_three_64',
    IEC_62196_T1 = 'IEC_62196_T1',
    IEC_62196_T1_COMBO = 'IEC_62196_T1_COMBO',
    IEC_62196_T2 = 'IEC_62196_T2',
    IEC_62196_T2_COMBO = 'IEC_62196_T2_COMBO',
    IEC_62196_T3A = 'IEC_62196_T3A',
    IEC_62196_T3C = 'IEC_62196_T3C',
    IEC_62196_6 = 'IEC_62196_6', // Added for Type6 support (Tork, Ola etc.)
    NEMA_5_20 = 'NEMA_5_20',
    NEMA_6_30 = 'NEMA_6_30',
    NEMA_6_50 = 'NEMA_6_50',
    NEMA_10_30 = 'NEMA_10_30',
    NEMA_10_50 = 'NEMA_10_50',
    NEMA_14_30 = 'NEMA_14_30',
    NEMA_14_50 = 'NEMA_14_50',
    PANTOGRAPH_BOTTOM_UP = 'PANTOGRAPH_BOTTOM_UP',
    PANTOGRAPH_TOP_DOWN = 'PANTOGRAPH_TOP_DOWN',
    TESLA_R = 'TESLA_R',
    TESLA_S = 'TESLA_S',
    DC_001 = 'DC_001', // Additional to OCPI spec, Indian standard

    /**
     * Added for AtherGrid
     */
    IS_17017_2_7 = 'IS_17017_2_7',

    /**
     * Added for GMaps
     */
    is_17017_2_s7 = 'is_17017_2_s7',
    ola = 'ola',
}

// #OCPIv2.1.1 
// 8.4.5
export enum OCPIv211ConnectorType {
    CHADEMO = 'CHADEMO',
    DOMESTIC_A = 'DOMESTIC_A',
    DOMESTIC_B = 'DOMESTIC_B',
    DOMESTIC_C = 'DOMESTIC_C',
    DOMESTIC_D = 'DOMESTIC_D',
    DOMESTIC_E = 'DOMESTIC_E',
    DOMESTIC_F = 'DOMESTIC_F',
    DOMESTIC_G = 'DOMESTIC_G',
    DOMESTIC_H = 'DOMESTIC_H',
    DOMESTIC_I = 'DOMESTIC_I',
    DOMESTIC_J = 'DOMESTIC_J',
    DOMESTIC_K = 'DOMESTIC_K',
    DOMESTIC_L = 'DOMESTIC_L',
    IEC_60309_2_single_16 = 'IEC_60309_2_single_16',
    IEC_60309_2_three_16 = 'IEC_60309_2_three_16',
    IEC_60309_2_three_32 = 'IEC_60309_2_three_32',
    IEC_60309_2_three_64 = 'IEC_60309_2_three_64',
    IEC_62196_T1 = 'IEC_62196_T1',
    IEC_62196_T1_COMBO = 'IEC_62196_T1_COMBO',
    IEC_62196_T2 = 'IEC_62196_T2',
    IEC_62196_T2_COMBO = 'IEC_62196_T2_COMBO',
    IEC_62196_T3A = 'IEC_62196_T3A',
    IEC_62196_T3C = 'IEC_62196_T3C',
    TESLA_R = 'TESLA_R',
    TESLA_S = 'TESLA_S',
}

// 8.4.8
export enum OCPIEnergySourceCategory {
    NUCLEAR = 'NUCLEAR',
    GENERAL_FOSSIL = 'GENERAL_FOSSIL',
    COAL = 'COAL',
    GAS = 'GAS',
    GENERAL_GREEN = 'GENERAL_GREEN',
    SOLAR = 'SOLAR',
    WIND = 'WIND',
    WATER = 'WATER',
}

// 8.4.10
export enum OCPIEnvironmentalImpactCategory {
    NUCLEAR_WASTE = 'NUCLEAR_WASTE',
    CARBON_DIOXIDE = 'CARBON_DIOXIDE', 
}

// 8.4.12
export enum OCPIFacility {
    HOTEL = 'HOTEL',
    RESTAURANT = 'RESTAURANT',
    CAFE = 'CAFE',
    MALL = 'MALL',
    SUPERMARKET = 'SUPERMARKET',
    SPORT = 'SPORT',
    RECREATION_AREA = 'RECREATION_AREA',
    NATURE = 'NATURE',
    MUSEUM = 'MUSEUM',
    BIKE_SHARING = 'BIKE_SHARING',
    BUS_STOP = 'BUS_STOP',
    TAXI_STAND = 'TAXI_STAND',
    TRAM_STOP = 'TRAM_STOP',
    METRO_STATION = 'METRO_STATION',
    TRAIN_STATION = 'TRAIN_STATION',
    AIRPORT = 'AIRPORT',
    PARKING_LOT = 'PARKING_LOT',
    CARPOOL_PARKING = 'CARPOOL_PARKING',
    FUEL_STATION = 'FUEL_STATION',
    WIFI = 'WIFI',
}

// #OCPIv2.1.1
// 8.4.12
export enum OCPIv211Facility {
    HOTEL = 'HOTEL',
    RESTAURANT = 'RESTAURANT',
    CAFE = 'CAFE',
    MALL = 'MALL',
    SUPERMARKET = 'SUPERMARKET',
    SPORT = 'SPORT',
    RECREATION_AREA = 'RECREATION_AREA',
    NATURE = 'NATURE',
    MUSEUM = 'MUSEUM',
    BUS_STOP = 'BUS_STOP',
    TAXI_STAND = 'TAXI_STAND',
    TRAIN_STATION = 'TRAIN_STATION',
    AIRPORT = 'AIRPORT',
    CARPOOL_PARKING = 'CARPOOL_PARKING',
    FUEL_STATION = 'FUEL_STATION',
    WIFI = 'WIFI',   
}

// 8.4.16
export enum OCPIImageCategory {
    CHARGER = 'CHARGER',
    ENTRANCE = 'ENTRANCE',
    LOCATION = 'LOCATION',
    NETWORK = 'NETWORK',
    OPERATOR = 'OPERATOR',
    OTHER = 'OTHER',
    OWNER = 'OWNER',
}

// 8.4.17
export enum OCPIParkingRestriction {
    EV_ONLY = 'EV_ONLY',
    PLUGGED = 'PLUGGED',
    DISABLED = 'DISABLED',
    CUSTOMERS = 'CUSTOMERS',
    MOTORCYCLES = 'MOTORCYCLES',
}

// 8.4.18
export enum OCPIParkingType {
    ALONG_MOTORWAY = 'ALONG_MOTORWAY',
    PARKING_GARAGE = 'PARKING_GARAGE',
    PARKING_LOT = 'PARKING_LOT',
    ON_DRIVEWAY = 'ON_DRIVEWAY',
    ON_STREET = 'ON_STREET',
    UNDERGROUND_GARAGE = 'UNDERGROUND_GARAGE',
    PARKING_TOP = 'PARKING_TOP', // Added for some CPOs 
}

// #OCPIv2.1.1
// 8.4.17
export enum OCPIv211LocationType {
    ON_STREET = 'ON_STREET',
    PARKING_GARAGE = 'PARKING_GARAGE',
    UNDERGROUND_GARAGE = 'UNDERGROUND_GARAGE',
    PARKING_LOT = 'PARKING_LOT',
    OTHER = 'OTHER',
    UNKNOWN = 'UNKNOWN',
}

// 8.4.19
export enum OCPIPowerType {
    AC_1_PHASE = 'AC_1_PHASE',
    AC_2_PHASE = 'AC_2_PHASE',
    AC_2_PHASE_SPLIT = 'AC_2_PHASE_SPLIT',
    AC_3_PHASE = 'AC_3_PHASE',
    DC = 'DC',
    AC = 'AC', // Added for some CPOs
}

// #OCPIv2.1.1
// 8.4.19
export enum OCPIv211PowerType {
    AC_1_PHASE = 'AC_1_PHASE',
    AC_3_PHASE = 'AC_3_PHASE',
    DC = 'DC',
}

// 8.4.22
export enum OCPIStatus {
    AVAILABLE = 'AVAILABLE',
    BLOCKED = 'BLOCKED',
    CHARGING = 'CHARGING',
    INOPERATIVE = 'INOPERATIVE',
    OUTOFORDER = 'OUTOFORDER',
    PLANNED = 'PLANNED',
    REMOVED = 'REMOVED',
    RESERVED = 'RESERVED',
    UNKNOWN = 'UNKNOWN',
    PREPARING = 'PREPARING',
    FINISHING = 'FINISHING',
}

