apiVersion: v1
kind: Secret
metadata:
    name: stg-pulse-ubc-ocpi-adaptor-secret
type: Opaque
stringData:
    NODE_ENV: ENC[AES256_GCM,data:BUhK,iv:/iMMgLLmksSlmT4XNpk6tVkIG0kVIEFdR5Q/O8KzDws=,tag:2Cwj6zcYmZjswaCl9vRggw==,type:str]
    REST_PORT: ENC[AES256_GCM,data:MYbsGg==,iv:7/EkvlEcpRpWirHq3n74UF/qm+oIkLNkoett7zzTVtQ=,tag:EhgX5EcElgXpUjJsZAtdQw==,type:str]
    LOG_TIMESTAMP: ENC[AES256_GCM,data:5nhavA==,iv:ZUXXbUHTkyYefE1zvwx+k++PGfgTheWCx1JgvYlOSb8=,tag:kyUOUL+s10rD8HcleJ0wpw==,type:str]
    #ENC[AES256_GCM,data:Gvadkhrf4iKAn4muRtgXdenhuhukyg==,iv:WF/uKH7VspLGiCxg9VjC/khLKNqcSXGYeVcv1cFuyUI=,tag:zxCO3uQWXF5sst7Lf2wOVA==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:emo6y8RVNe5XtaCNTZ+Xlu/jNNLfuy9foP3DdKMSyh4cJXgcmps7cbEqi0Zphhb/xHJYejcUABx8HhcPhVgFHLVoekaD6QDoOVhbg2hdpIDCWyEtb9pNlBHPhoMqkqrM5SFT5YobxIU4Hf0vsC2knWgyaL6ejxLaz9tIEcw5L1gkkahI4UFYuF2u7jPCzCRKXQxTKb/ZxHeCMdfUlLiT6jlRTK6YTkgJf+hF36Z4MVhcVPz3K76EQyhIseXGTkI+i0s5f55jNu/iYAOWw0Z9BdXLczpQq3c=,iv:DMMYqHVaZpqCt3w/DA2GPeISiV/YdqkLNjdV5jFfe/g=,tag:Kv1sSDtkB73wfy4sfFWvHQ==,type:str]
    #ENC[AES256_GCM,data:L3BsJDYg14kP2iJ+TQgyMIB+Jw==,iv:EVDy2z0otAZa3s4JsIZLk2bYHqe2cjzBpEP3pwDIjlU=,tag:VGyPDzPFOrPHcqURML1nLg==,type:comment]
    OCPI_HOST: ENC[AES256_GCM,data:S5eTZlpMbfWqZ5zd2Gl/C5ozACkPcw3MbLZApeGP5Bw4UcZotIpdyPmIXNa3GoaMAg==,iv:bK+6GJhJyYjr7fdDbMTjPlVK8dBL21YOLJfaJIsk5lg=,tag:P6U8ggY50u2ZipLsgIx9yg==,type:str]
    OCPI_VERSION: ENC[AES256_GCM,data:0JnOJY4=,iv:LH1EJm7duGldhnT9d15QxW91w62brlfzVwra84mBxPM=,tag:+SqjvC5AdtofGUTJwz4WyQ==,type:str]
    OCPI_PARTY_ID: ENC[AES256_GCM,data:4tYF,iv:PpQYUxE21Rnggcf9FcGmtbnTIn9lMf4Yp6YbX9pF7kk=,tag:bC6UnVO+QOJh2/p2MZRjEg==,type:str]
    OCPI_COUNTRY_CODE: ENC[AES256_GCM,data:MnY=,iv:ySJvqoovVJg2HIBLuODbMvr9ZfcmxcL/f7KIdspZa4U=,tag:Nr3YgBGsp54Cc4vvDTzLdw==,type:str]
    #ENC[AES256_GCM,data:SDB/p72yZxgzGs9Kx1vz7VEaY4RxibRAl78cMuMqY+6brhnyJTQ1+Cu7XzJN,iv:iIMvscf8jLCJ+e5u5NLltX8sxQ8gZPFAMiP6tR87wVE=,tag:t3tTDlZgUu8zNgBx4mdT0A==,type:comment]
    CDS_BASE_URL: ENC[AES256_GCM,data:zrehW4f4y2bwj01ATezajbvbk4C5VcU=,iv:R1s6q9InM9KUy8kNrv8QSsZqXhNE9xOYHMtj+t17ysk=,tag:H64jda0lR0VZh8Wt/s0zkA==,type:str]
    CDS_API_KEY: ENC[AES256_GCM,data:/6b94f5KzTv7+pB4RRQKz2/Op8AgzNjlXAP2yeMRVtQpb4u4IXkzMzs3noX6UxrH,iv:k+kmHfEHQvImaMdLa3U3eX80LOF8Em0wWN1SUlN+o5Q=,tag:NES+66q6BBSDz0CPfnX30Q==,type:str]
    #ENC[AES256_GCM,data:JsNP+WR2tSGjCLAAxCkGwKWAOakHqA==,iv:y5PnSPvwYv+0kX0uTlEq4ZQHCTF9r5kctz/T7krvM5g=,tag:Vdq/fBF1zrvskb0P4lYZPw==,type:comment]
    LOG_LEVEL: ENC[AES256_GCM,data:lG+v0Q==,iv:fHnurJzBc57y47jXsalLTZBFMkqUbyG8QaiyBctf+oI=,tag:MdWpWRg2nyQBbI5GcIfyxw==,type:str]
    CLOUD_PROVIDER: ENC[AES256_GCM,data:8Q8ycPw=,iv:ZUEnFNHucVroOfZxfu/o5pytbX9B5A4TkICOqA1IYKA=,tag:51zw30vPPaz+fYklI8tE4Q==,type:str]
    #ENC[AES256_GCM,data:BJIlGKPqn6U=,iv:/vb7CdYVNLzEJeiScCocg1MmV6Mzwxt1rgw0y/nrDE4=,tag:h62z1GbzN1PAjU/Ng7SDuA==,type:comment]
    EV_CHARGING_UBC_BPP_ID: ENC[AES256_GCM,data:kfU/M+GktbLqVavS0fM6b3w4IjLZdB5D,iv:/zFdj3vhZ5hOdtkxqaYnqw8AV5OKxL6PP/QalfUzCCE=,tag:JlYEleUHuXKKYjZmRfzg7Q==,type:str]
    EV_CHARGING_UBC_UNIQUE_ID: ENC[AES256_GCM,data:La/xui3Ay9hZ5p/K0v01eFMavJF2+E3oNoWhz65M1tWdWggvwZNVRLe7x90EGverDlkLP/7i,iv:EULTvsp3IVUtevxzr2O4cg23eLVVA0INIGn5CjCMJKA=,tag:ayFd3234aW2+5ezerG6JNA==,type:str]
    #ENC[AES256_GCM,data:6U22kg==,iv:mJB/UFBqn3/B/shw1r1CQouXN6p2VAG6FpoY8pLZgxQ=,tag:UrqkmHPZMF2qVJjJxEt3xw==,type:comment]
    EV_CHARGING_UBC_BPP_CLIENT_HOST: ENC[AES256_GCM,data:sShP4yC0U02uYK3qtvBJ1R833LVAOqiTNp5py6TE5aFP64NtTg==,iv:ZacX7X6p4RdPfDVHg3BGGsWhsZzfLxlHhhJg13Bd29E=,tag:J86y/NYGPs+MiAHDTkxhCA==,type:str]
    PRIVATE_KEY: ENC[AES256_GCM,data:95Vp+ornss8OGNwfiDRIltW+iouFVwcp9OdIIRZxIVhBB6OwgL5pHX7KMpvT0yZ5ldaulufftO1VGf2qK1Zl3q40GJjsbFw4+cbD3y1sWvDVTiynFcZnVg==,iv:mgngwZKwF52wIHir9IpA+m35t9+zLApQatR1i+mcs84=,tag:i01FFLZXW8SgR8I/HqhOWA==,type:str]
    INTERNAL_PAYMENT_LINK_HOST: ENC[AES256_GCM,data:szrB5VXkuYlEzNH0zvQsEkAvzfmVLxrS5wAb4uzQVGFWFAL0qXyZ3Yt5Iw/+8Jic/A==,iv:/WRJRNLf83j5qt2IcTilX3VB1w8Iasr2/tXY8Jx26g8=,tag:1qPS/YmYnYnx7tpZYwjMdA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pulse-energy/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-01-13T09:32:57Z"
          enc: CiQAHUiyboSZA5pEmet25P0m54NqotExfF7kvZmhiAwfw2xcTsYSSQCT28oB5g0rQi5E0f6sSMqBROzOlyoqGMw65tCTNYE53leuD2o0vuoeqJg7lIxZfwKnT5TAXsa8wtlIXMsnZX6aUncag6ko57Q=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-13T09:32:58Z"
    mac: ENC[AES256_GCM,data:6blyu8hD1qZxfNzKA/Ovb5pC67Gkfq8zHsmziD1/O3IOjbxhbCEqOktzjfoCyyJRgq/ozmJa4/78Pp2ArWitLRYQXAwJVFRWdX6gxZ/cH60wXM7vXyw1ybXJzzVmoBt7ZbhUdH+dzeniEtjQZDtpevt0dZI2muaaIIjkgEkWAwo=,iv:1WdFUnZZWNDFnep9dVBe3qskb4etebRTIpmRVpIZC2c=,tag:cwxcL8watJ8/kNrjF3utUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
