apiVersion: v1
kind: Secret
metadata:
    name: stg-pulse-ubc-ocpi-adaptor-secret
type: Opaque
stringData:
    NODE_ENV: ENC[AES256_GCM,data:kLs5,iv:GuLZS9zoj0cVo9JkDgGpQoy54XAKgWejE19lokm71fI=,tag:o3qNM/ArYYtXEoBj0t9nTA==,type:str]
    REST_PORT: ENC[AES256_GCM,data:uYBgPQ==,iv:BuLBKv8d/kRO09umXQv2D54lhFJqBlPC98z0l8QeS38=,tag:Gh3qnAYPppaBKHak2wDxXA==,type:int]
    LOG_TIMESTAMP: ENC[AES256_GCM,data:eUEKeA==,iv:Wis4X2/YjTIuMxQFd7seTllNqFbYCblHXqq3KiJp5J8=,tag:9SNZbYu5B8X7Mczy9nZ4Ug==,type:bool]
    #ENC[AES256_GCM,data:EtslHCqamZnmWO0XiZxON9e08NO4Vg==,iv:797XvCbpM+Xcyktd77gJjiZInsynXBjWyvCY2cYmsVs=,tag:wjsdQPQru6SqiVmOC/CTkw==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:CIqLYZiudv+ogECU6Of0JiITRjPDqyrfapl4yms7KPhqeW7UZ5fbmHnxxAEkx76ydUUH8Zhn4nTbUIO7IokbpKFx0h8AJWcDHh5S8+7qQ8f0sFzhuPLbN0yvRdcsVI6imugAwPo3uTcqHaJozLjjcVvbVzV5fYQU4VER9CUULTg6QQkYnoeWKV6OZHi2ZmsjwI2DsDf6dfUOLL7MSkua/zAvPVahL31A/+O7a4aiFqDhuxMTfJ79i528AoY7/EXbljngbWqi+CmIMCOT3JOQmPNw76Tj5YBOTIsTNRSkshCppTt2pIafST0=,iv:JkibPlib9UEC1DRDwY5CtKnbo55Uz1+VbAmYz0/MAkE=,tag:T373oVHZq/uS5NKF1u6/Lg==,type:str]
    #ENC[AES256_GCM,data:wZY2WyZp2eenuQ9x1/NkPLguNA==,iv:hPrhT71r0Vk+S0KJdSNJ36HyaeMuKUKoHUvedndH0UU=,tag:m+CmQNTZgn0dE+fN2m9o8g==,type:comment]
    OCPI_HOST: ENC[AES256_GCM,data:MatNen7DEiLF5m/MFUh39QUuppYxcYLAyXuiU2UZE1xJ8Rr6AL6mi52lY+Qpp3ZLhA==,iv:jvQh5YMcrdy5fNxtnhrdhKCLMAOvft8fV7hFqtBBvEg=,tag:Fsb8ILTJu3zVXom9RPUSUA==,type:str]
    OCPI_VERSION: ENC[AES256_GCM,data:8zEbQNw=,iv:h28jXq/wApA0D2dTPC/REVwlyCkG5mQmO2uYLXz2oN4=,tag:3Ae5d71F1yovFJyOWgLVVw==,type:str]
    OCPI_PARTY_ID: ENC[AES256_GCM,data:SvUK,iv:l8JhnBWDtzXXWwPB11rwkxbIF5f5d+oxX5Lnip/Nkr0=,tag:j04uVUvLTq9jU82Llh61Bw==,type:str]
    OCPI_COUNTRY_CODE: ENC[AES256_GCM,data:HH4=,iv:wgufrhu8vvekiuZqRaodQDuI2EuR+c084EAYHMZr84o=,tag:mo0yendmPgTavamFVn42VQ==,type:str]
    #ENC[AES256_GCM,data:VOR4sHiXpfqmhDYfevsQXyw+D7goOnYg2jUIsfxATcQ+UBLSlRuNs0NJ+Hpk,iv:smJjGB2Ir5IwSdXK2XCULK69kiECqijrJdzB+0xNcuo=,tag:IqiVhUxT2d9Z3z7NenyXsA==,type:comment]
    CDS_BASE_URL: ENC[AES256_GCM,data:rEcqA3uSd1DMUwFcctnvyzxhG09BWBc=,iv:ok/xLNRxBrdkFO3sYBotCRQygunkxH7bAPIgkNdEeSU=,tag:g/iurG1QpeKj5GCoVyHAVw==,type:str]
    CDS_API_KEY: ENC[AES256_GCM,data:gzJhaNSHZRno+QLFKYvpLy3z5X4cpgHi2563nl+sbcWhjAeh6oRigK2Z1K3EODAX,iv:KDR8OYejCE6oYn0HLOKU2O5Sz+egq7/T6baFm1GxO2k=,tag:wIETzVnAB3QfxPYFMS5sBA==,type:str]
    #ENC[AES256_GCM,data:EtZyP/Me4sDm8PjELgoS8BYbM6Tu9g==,iv:rp00IMYeU84QTOE4kNxQvyYW5scX1ApMsSaiHO0Z0jk=,tag:NH7GK1uXa04Er1nH8AtkGg==,type:comment]
    LOG_LEVEL: ENC[AES256_GCM,data:k0gXIg==,iv:yrFBfNiuIyvvl6+8oN4uFdTcCfgwZKKoaUceZQO2HXo=,tag:X74yWNtkceSyR3wEqHPiEg==,type:str]
    CLOUD_PROVIDER: ENC[AES256_GCM,data:msSvHuI=,iv:tZKxValnyynVKgm7ummTy/kYr7umOtvz4NxS2gh9+Hk=,tag:NEoV2ALRZJLqvysJ+yEwVA==,type:str]
    #ENC[AES256_GCM,data:Rs2RpIg917w=,iv:adWHodorLdmU0nG72BvE0lyTMuov14/7K6a3L67NY7E=,tag:UUxQ3GXv27HdHZUHViugtg==,type:comment]
    EV_CHARGING_UBC_BPP_ID: ENC[AES256_GCM,data:fsX7xdKTD4oETFOAUgqymVUiFsLO/Beg,iv:35N6Jfnpum8ekTMQ0tURsundyB1QNZk2z5A628w91DU=,tag:NwWTd1R8EOniirGwswj5dg==,type:str]
    EV_CHARGING_UBC_UNIQUE_ID: ENC[AES256_GCM,data:cOa0oBZUsPYXZz9kC48+hdDAI2RVcpQ1f2Wpm5LF9qpl9WuZgeJIDcLam9kqYg7g8+TMwiVK,iv:6RNZ+C/OlyBwaJ6ZScQhrE46qFd1c3M26kznpOwKzeg=,tag:sxx/3SKeoCX/x5FcwNAvWQ==,type:str]
    #ENC[AES256_GCM,data:VECdNQ==,iv:GYBOFahXG5Y5hkBAvV14geGYvWKgzwbRqdhDfGQFr3Y=,tag:+3gS4dp5BvdNcHFWjtxpgQ==,type:comment]
    EV_CHARGING_UBC_BPP_CLIENT_HOST: ENC[AES256_GCM,data:4ZdGTe8HmvlYhRNvXX9aEf64udmIM78YgJRY,iv:gsVpQs3AGFGc/bV8NZAoSVmDbDom/HtfSZjlhbYmdhs=,tag:lxWhrNMauExytzNXWLXY0Q==,type:str]
    PRIVATE_KEY: ENC[AES256_GCM,data:T3dbMlyhhhECKhFue+wyupTS0DKvtoZEuFw7jisfQ+63eYX0pu1cZnx/cqPDuNIw3CC8EKQZIjWFBqpwMlyd/3+L2nafvTaHq13YxT4fdEeDaw8bQy3cbw==,iv:bahsS8vlR7qpOJaq1NGvoywnBnPJjLk+8wIpF7zStSs=,tag:8sTvItZWkasthyHGrDsGRg==,type:str]
    INTERNAL_PAYMENT_LINK_HOST: ENC[AES256_GCM,data:fcBVKwCezhkGjFTVWeFC28Cqjv4ev4USlcLfrVGM+4jIvPMzGQF9yBW6B2n6gRu6fg==,iv:0XXW7iAjK82DPqtDA4WmfyOobKDWnOtdr2dyOKycX4g=,tag:NyWjr8nvvDmomPSqIOgopg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pulse-energy/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-01-09T13:11:18Z"
          enc: CiQAHUiybjE4Y7Boo54y3tqB8eLJ31PXj1HzKWdf56KaLNGBNooSSQCT28oB+QFSFr1T2tzFdV8q5QP4KTTCsAwI9ayoQIUBJ6T5zNEP0KPnA08KXkVND7r0Dn7JLcek56YeerULF0DmKwUkH7FarCs=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-09T13:11:18Z"
    mac: ENC[AES256_GCM,data:1gOEXayCg37TONGZbfBFOZ2vdHxcXhEJHevlT1D3MGV5bDFr2oXZwUdYUSXKsqLRDBmmy/TBcEIunqmf2KuNbMS4r6IWpsi8D0r2LNayU1zZ19MprPyRfuK3vJTFqpWT1Tu6PgUTzOrPQ+nWseo94+pW7jHq3BU2ROdiRRk7CZo=,iv:h1IET4+ol+3wjiFQsnp7mJungjcbmFW+oQ0y0eq0oug=,tag:fMBEJ2zEKGomFHaQsZ7TiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
