apiVersion: v1
kind: Secret
metadata:
    name: stg-pulse-ubc-ocpi-adaptor-secret
type: Opaque
stringData:
    NODE_ENV: ENC[AES256_GCM,data:qjUG,iv:pvZ3L6nnl54TzgOYHxNK/kdj4cZIUXL9FPp0nBATH0U=,tag:STUkfu6xW3X8pF6yOljgQw==,type:str]
    REST_PORT: ENC[AES256_GCM,data:pc+5cg==,iv:LBSSSiRIB48/NYUsRMEVKMU9h/64ejGxkugssTSssig=,tag:BpF7h6j8Yaxl/ZHK9rV3Ig==,type:str]
    LOG_TIMESTAMP: ENC[AES256_GCM,data:VV77Rw==,iv:YRHmJGHgqcnLlloL28XlpOwXYGwOzxjjqFyKVDTNUE4=,tag:eQ4Sn0I9SAX1+xAi8Fr3WA==,type:str]
    #ENC[AES256_GCM,data:1YNUqEsePfsAxt8wCNt8l7Slt9dT/w==,iv:xDzJlDudFgczATsI+V0hXyQ6vu/kQMBqTGWtDOw9GKY=,tag:yzlGPYLruadfGUtv9pkbnQ==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:4QQIGYOFWve1ZyXZysuVf8Jt0PmQvSaTIc0pqybOAw3w2AwUuobQNpVNOUMu8V6pTwwNll4nsE8Q41LAF9ouQBbmb5jFTwAdjNHz9D5l7nIDVMEtN9sXaqWHUJHpXGiOpWyFm1jxWJRftwesIShcR9e4h0zCyFy0Yp4veHS0/cTcI6AvAfOCJ7nbH0gomyljR/cHi0CUnHwNN8UnMGCIhY9L7h2iL+vz8cIopZHKo9Ncn3qJjKK6L0TjPa775KGXbivWmoxe83ApYPJ/S8QNGAhA4oDKpc0=,iv:fuRIlVKxuox3sjY2xQPFkTuG3RX5PPSkviyL1mKfezg=,tag:+ZM3MahMXkcjpvSHrL82eg==,type:str]
    #ENC[AES256_GCM,data:Ym/ggM7SNYRMmOZhz/gJTUO5mA==,iv:FpUmNlhF+hLZleysNl01IHp77BrDQW0PUo+qD3FfkA4=,tag:+GifnJ96Sq6KZjWIDUxrDg==,type:comment]
    OCPI_HOST: ENC[AES256_GCM,data:eNBhwJtGbmjG3e5daRFjn7Ga3OTW/2mS1PmVrbotdsNhQE4HGb9xaT7X/xdb8tMpiw==,iv:qdg+977+L+0M9L4IvMfH6um1kSOjjEs3nBFYfHPOzmY=,tag:cN5i/ZqPvLvsNZy+k3bxtA==,type:str]
    OCPI_VERSION: ENC[AES256_GCM,data:K0reA0M=,iv:4CLUxynImkWT9xeTq4o6pTpYlKa+HQ8/7iJAmt948So=,tag:CWXwrzQa8WT6aUfTQtNttw==,type:str]
    OCPI_PARTY_ID: ENC[AES256_GCM,data:QVEj,iv:2QM/QCnh55V5v9OI+auKfIVf29bBaDjFe7hgjAbgqkU=,tag:WpGtyqcKl1uCkBDB7ziJlA==,type:str]
    OCPI_COUNTRY_CODE: ENC[AES256_GCM,data:TkI=,iv:q3bYvLp3qIRu2cnPViL16AGuEvl2rf0niXrUo4/CjMo=,tag:ht9EodOcRcInZdMRAyQsbQ==,type:str]
    #ENC[AES256_GCM,data:m8lkDDp0bmAM9IAvN+HXE4Y+/NgxVgrdHXuPn4YRbkrpckt83HjQa99WpCuw,iv:4kDAe/y2ytEi19jez9Sg6+MVJPgwGSDIqrtyNTySFY8=,tag:4ayTv7PyWjtZIuzeH8ak2A==,type:comment]
    CDS_BASE_URL: ENC[AES256_GCM,data:dyK4dx7KH007hhuZ8gN75bCytjLQCFA=,iv:jtvwd7HnVxxMNmT3DYjjwvw/aGrr2fh3e5Zz5+7y8M4=,tag:LJScTf+cMW+LnbQozkt/pA==,type:str]
    CDS_API_KEY: ENC[AES256_GCM,data:bFpEccEUgD5+frksO2GxsgCkutvi5nNa8/iZf8ge5YoySKLEO+UyMEvKsNYrgOVf,iv:QLFVT6A1mRD0fjCbOfKvg8Hc6r1+KjsoQBCpvbF6ZpI=,tag:rb1xfqAEyPDEEysFp/gdbA==,type:str]
    #ENC[AES256_GCM,data:NuLsIXra3mLbRzRQeo9EiC4QVvnARA==,iv:JURd1VWcf9A0s+qD2EfjByClFfEaFJiaVfFH0bHje1Y=,tag:+8n1tPcYX7P6FvkDaTy0Sw==,type:comment]
    LOG_LEVEL: ENC[AES256_GCM,data:iYlDzQ==,iv:MiLxoGH2s1LURdBsK/jD+Bd2woXAAA1yBM2vEns4OvQ=,tag:sUBo0oT13eUGKW+93yKHyA==,type:str]
    CLOUD_PROVIDER: ENC[AES256_GCM,data:3T1PweQ=,iv:9FRdaQqP1wObXnB4AVgDe0+dHQDd68tHZ3nE/LIhwcg=,tag:IiinO5FOObxEVJk64+ZJXg==,type:str]
    #ENC[AES256_GCM,data:AFufyQs/W/8=,iv:GLVFmg0gcRVOJFw0klG4uoEEuDrbc47GYrVnaE3Y/Hw=,tag:pBgQcOEXW4jVsCx9dRxfLA==,type:comment]
    EV_CHARGING_UBC_BPP_ID: ENC[AES256_GCM,data:aWuFwwNJZSKGiKj2VcjtwBVhY/UD,iv:lT5sErbbziU4z3puk3l8Nly2B3en1LW+7msqbgUOQZ8=,tag:B9sz42pGpTbvw47XiJb6ow==,type:str]
    EV_CHARGING_UBC_UNIQUE_ID: ENC[AES256_GCM,data:XgBH7nx8vCnDl7BNecAkpbcTLieNa425NAmvsapEF1uFd+YYlo5C0G3BBl8WeE1lwYevtL36,iv:gNkduDWzm/+AmmSVaN1jfiaMKMUXDUAEptc+sKOqqqc=,tag:Op2f5aIU+1SecSYzz+3vGA==,type:str]
    #ENC[AES256_GCM,data:iY6TGg==,iv:QIPKDO0LuzUa+qU6OehHHURGpNFDGeSHB2k00vxCznM=,tag:M6z8KO481s1WbVeT4EER/Q==,type:comment]
    EV_CHARGING_UBC_BPP_CLIENT_HOST: ENC[AES256_GCM,data:nDHJIvYiNFflskUrHvdQEIUwPthENgXK73HmkOp9QgKCcglj8w==,iv:yFni+Ek64e96v6GNd6sKesXeex4Bf5nnZur+jqs4h6I=,tag:RGT35vWdmZTx1+SkpSK/Jg==,type:str]
    #ENC[AES256_GCM,data:kZb5gxQ6tHPjKmvfaQgL+8BM0/Tbr5ab1z/Jn6wkGimmUm8mcjHytUTEyrqLkAzKMgVTRzdFRLjCG5DjjZPflkWDfmr6+Dgnua1onWwqm6/8no4grdjr3FF6p7+Pdvt3rNOte6Cy,iv:kktm+zHyB6MpUf5hLdksUCrSiqO9Hqwp5WwNZGzbplQ=,tag:o0Y4OnCbH51R6Rx2570W6Q==,type:comment]
    PRIVATE_KEY: ENC[AES256_GCM,data:RPHt31iBRUI5olB0ru/3ASj6gPiaB8GQoI23b46SjJmH6dYrZJqGE9rUHLQ=,iv:GULeCmbAf1K9ZgflLrfqpIx+DvNbnqwioCvRvLL8npY=,tag:bbUTHPdsB4a5arE5UABQhQ==,type:str]
    INTERNAL_PAYMENT_LINK_HOST: ENC[AES256_GCM,data:ZBJEtaqpo6ak974WSUJlUAn6Zp/o2pwY18IxipM72DOmFVefDgXiSBG4qi//ZNl1kA==,iv:vQddm5l9DuQFy5Rq2qMszRPg37yLjTxbmzlBu63+ghY=,tag:TlkVOJrgoXLR3vT0m556zQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pulse-energy/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-01-14T06:20:15Z"
          enc: CiQAHUiyblb+hrKZSR50CvSDBQDQhEUWf2W1FdlSdzd7kdASk8gSSQCT28oBoOsh1YoW3vsGEcrO6TlMvfKgsKjlUJuWmLtNrk3wkDD6NFCMTwZO6/GGdbSf90BvvWgXflDdl6xa4P0qvf91066U8Bw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-14T06:20:15Z"
    mac: ENC[AES256_GCM,data:2rXHF1qwi9AGi8ss4QidmkhO6a0jBXJkjqEB/Yg92ACjlgn/F6Q45NKtD3kdWOypiTHZBuZ4vghSaxfaXhzlDNXBPiH2RaYhgGFtvGb/Dt4VteCfUFPeO6PPvBpDzX1Ae6DmUNB5UeLdxCGWFcsLK0uLV92/ao/TY5nn5XqLRyc=,iv:K3eSGoqcSM7fVdi1BKFu1XgexNxqvSflUO3yKpJwS8w=,tag:xuPbniUApkldkl2tE50tEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
