import { ObjectType } from "../../../enums/ObjectType";
import { BecknBuyer } from "../../../types/Buyer";
import { Context } from "../../../types/Context";
import { BecknOrderItemResponse } from "../../../types/OrderItem";
import { BecknOrderValueResponse } from "../../../types/OrderValue";
import { BecknPayment } from "../../../types/Payment";


export type UBCOnInitRequestPayload = {
    context: Context;
    message: {
        order: UBCOnInitOrder;
    };
};

// v0.9: OnInit order - removed orderNumber, fulfillment, orderAttributes
// v0.9: Now has beckn:id (order id generated by BPP)
export type UBCOnInitOrder = {
    "@context": string;
    "@type": ObjectType.order;
    "beckn:id": string; // v0.9: order id assigned by BPP
    "beckn:orderStatus": string; // v0.9: "CREATED"
    "beckn:seller": string;
    "beckn:buyer": BecknBuyer;
    "beckn:orderItems": BecknOrderItemResponse[];
    "beckn:orderValue": BecknOrderValueResponse;
    "beckn:payment": BecknPayment; // v0.9: full payment with paymentURL, txnRef, paymentAttributes
}
