const GLOBAL_VARS = {
    // OCPI
    OCPI_HOST: process.env.OCPI_HOST,
    PUBLIC_OCPI_HOST: process.env.PUBLIC_OCPI_HOST,
    SELF_OCPI_PLATFORM_ID: process.env.SELF_OCPI_PLATFORM_ID,
    SELF_OCPI_EMSP_PARTY_ID: process.env.SELF_OCPI_EMSP_PARTY_ID,
    SELF_OCPI_EMSP_COUNTRY_CODE: process.env.SELF_OCPI_EMSP_COUNTRY_CODE,
    SHOULD_SIGN_CALLBACK_REQUESTS: process.env.SHOULD_SIGN_CALLBACK_REQUESTS,
    PRIVATE_KEY: process.env.PRIVATE_KEY,

    EV_CHARGING_UBC_BPP_ID: process.env.EV_CHARGING_UBC_BPP_ID || '',
    EV_CHARGING_UBC_BPP_CLIENT_HOST: process.env.EV_CHARGING_UBC_BPP_CLIENT_HOST || '',
    EV_CHARGING_UBC_UNIQUE_ID: process.env.EV_CHARGING_UBC_UNIQUE_ID || '',
};

export default GLOBAL_VARS;