const GLOBAL_VARS = {
    // OCPI
    OCPI_HOST: process.env.OCPI_HOST,
    PUBLIC_OCPI_HOST: process.env.PUBLIC_OCPI_HOST,
    SELF_OCPI_PLATFORM_ID: process.env.SELF_OCPI_PLATFORM_ID,
    SELF_OCPI_EMSP_PARTY_ID: process.env.SELF_OCPI_EMSP_PARTY_ID,
    SELF_OCPI_EMSP_COUNTRY_CODE: process.env.SELF_OCPI_EMSP_COUNTRY_CODE,
};

export default GLOBAL_VARS;