import { NextFunction, Request, Response } from "express";
import { randomUUID } from "crypto";
import { extractTokenFromHeader, verifyToken } from "../../../utils/auth";
import { logger } from "../../../services/logger.service";

// General logging middleware for admin routes (can be used for routes without auth)
export const adminRequestLogger = (req: Request, res: Response, next: NextFunction) => {
    // Generate request/correlation IDs if missing (case-insensitive check)
    const correlationId = req.headers['x-correlation-id'] as string || req.headers['X-Correlation-Id'] as string;
    const requestId = req.headers['x-request-id'] as string || req.headers['X-Request-Id'] as string;

    let generatedCorrelationId = false;
    let generatedRequestId = false;

    // Generate correlation ID if missing
    if (!correlationId) {
        const newCorrelationId = randomUUID();
        req.headers['x-correlation-id'] = newCorrelationId;
        req.headers['X-Correlation-Id'] = newCorrelationId;
        generatedCorrelationId = true;
        logger.info('Generated correlation ID for admin request (UBC Adaptor)', {
            correlationId: newCorrelationId,
            path: req.path,
            method: req.method,
            data: {
                message: 'Correlation ID was missing and generated by UBC Adaptor',
                correlationId: newCorrelationId,
            },
        });
    }

    // Generate request ID if missing
    if (!requestId) {
        const newRequestId = randomUUID();
        req.headers['x-request-id'] = newRequestId;
        req.headers['X-Request-Id'] = newRequestId;
        generatedRequestId = true;
        logger.info('Generated request ID for admin request (UBC Adaptor)', {
            requestId: newRequestId,
            path: req.path,
            method: req.method,
            data: {
                message: 'Request ID was missing and generated by UBC Adaptor',
                requestId: newRequestId,
            },
        });
    }

    // Log if any IDs were generated
    if (generatedCorrelationId || generatedRequestId) {
        const finalCorrelationId = req.headers['x-correlation-id'] as string;
        const finalRequestId = req.headers['x-request-id'] as string;
        logger.info('Request IDs status for admin request', {
            correlationId: finalCorrelationId,
            requestId: finalRequestId,
            path: req.path,
            method: req.method,
            data: {
                message: 'Request IDs generated by UBC Adaptor',
                correlationIdGenerated: generatedCorrelationId,
                requestIdGenerated: generatedRequestId,
                correlationId: finalCorrelationId,
                requestId: finalRequestId,
            },
        });
    }

    // Get final IDs for logging
    const finalCorrelationId = req.headers['x-correlation-id'] as string;
    const finalRequestId = req.headers['x-request-id'] as string;

    // Log incoming admin request with full details
    const requestUrl = (req as any).originalUrl || req.url;
    const requestIp = req.ip || req.socket.remoteAddress || 'unknown';
    
    // Mask sensitive headers
    const safeHeaders = { ...req.headers };
    if (safeHeaders.authorization) {
        safeHeaders.authorization = 'Bearer ***';
    }

    logger.info('Incoming Admin Request', {
        correlationId: finalCorrelationId,
        requestId: finalRequestId,
        path: req.path,
        method: req.method,
        url: requestUrl,
        ip: requestIp,
        timestamp: new Date().toISOString(),
        data: {
            method: req.method,
            url: requestUrl,
            path: req.path,
            query: req.query,
            headers: safeHeaders,
            body: req.body,
            correlationId: finalCorrelationId,
            requestId: finalRequestId,
            ip: requestIp,
            timestamp: new Date().toISOString(),
        },
    });

    next();
};

export const adminAuth = (req: Request, res: Response, next: NextFunction) => {
    // Use the logging middleware first
    adminRequestLogger(req, res, () => {
        try {
            const token = extractTokenFromHeader(req.headers.authorization);
            verifyToken(token);
            next();
        }
        catch (error) {
            next(error);
        }
    });
};  