apiVersion: v1
kind: Secret
metadata:
    name: prod-pulse-ubc-ocpi-adaptor-secret
type: Opaque
stringData:
    NODE_ENV: ENC[AES256_GCM,data:Qw/zwA==,iv:l3zk+ZmUtJdTOHsuLCXYER7RVMn30IPwX8CTmN5Mc1Q=,tag:Qjne67m0UVT17ZDzZv1bbg==,type:str]
    REST_PORT: ENC[AES256_GCM,data:DmiJsA==,iv:8iRyM8kCdhyhcnei4uT6oTnuDvOgh/tzndTNXUC22d0=,tag:sZx8/NOnBasuheNYr3ZdNA==,type:int]
    LOG_TIMESTAMP: ENC[AES256_GCM,data:c8OqUw==,iv:eaADbG4yXEZ3zwgd/O+ESDmG05wfv36OYToBBNckTGg=,tag:NTUGcT5eakXHq8wqGKOyDw==,type:bool]
    #ENC[AES256_GCM,data:LDtk/otDbLJRV8M6AJAP275VK1/34w==,iv:KDHH07AUL8EKQjYlxlkl1w1RUMrDc/jEVTcBRrjK5EY=,tag:/2Hdh9jBX7ShY1LRxAzOzw==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:ENGvkRDxaDHI1g/luoD8W/w807U21DSEURBVdhbGVHUMZEQR85mY5BncCPleJ3YdMJAwo4ONWWGUR2UrE8lGDCN3hCxL37fWvIHumv4unjItS6sGSKvoyhJxKnG/bYjkUALjVZItRCIm3LhLwJEKKv9Y51y5j6mIGwcL56cSgNfbEdK/CnAnTXJPnUWmNivOwN467+z1CEvursCXvxnpI3VZ73cmfmpVAy//TSqivuWzopKvTOpAn9HjBE/hRa2crp8i159bEzLP+tuUkwpVnG27M8uYGobNsXWiYETjkzWFJn9sSzMOZQE=,iv:40uR16a3FM29Ew16YyqrzBhgwx62izNsvdVcJpGw+q4=,tag:b9w1IOBHWSjU1IPpI6nH4A==,type:str]
    #ENC[AES256_GCM,data:RhRQ2yx8m2G4hS68FDJLrBfU4w==,iv:tsO6tUNpl3fes5FS2Nx0rfqZeT8fT4hrFFc43IltpTw=,tag:BRYDOyaugzHhpGKWZREktQ==,type:comment]
    OCPI_HOST: ENC[AES256_GCM,data:hvKomKj+bSn55CTroFUl8y9m1WVIEwZqlcBRZFX/BZXfvmZqvowOqON21Nd0,iv:h+rIKe4BbUvEYn2tw75jrvUxS5tIzSLRSW06GHRM3I4=,tag:9KJGkXKLgQbLL5nwEuqzOw==,type:str]
    OCPI_VERSION: ENC[AES256_GCM,data:1l2GhCY=,iv:/FNzeEXPuUphYXsKHWnUgPHEv8YwPZp6skppci3jlow=,tag:bbIe24CCmYC8Ngj8HBedVg==,type:str]
    OCPI_PARTY_ID: ENC[AES256_GCM,data:t6nJ,iv:cSMDLMNY0mH/kZW0nHHVCmEYcNzFy2DBwU0WHiC5gIw=,tag:o8oxx5VpxcTsFEutUTUJnw==,type:str]
    OCPI_COUNTRY_CODE: ENC[AES256_GCM,data:dM0=,iv:C7cZRedTFcrrPusN8AlNlYZu2v5U6tM44ExhN4qjLC8=,tag:fcdCDJLpQFAKO6gtnCjPrw==,type:str]
    #ENC[AES256_GCM,data:r2HSeHfw4+yI21X1Yn0Mc2NcK0ERQf/7Cl6bsEf/tTmaMzOEm0yKdqcfVQbl,iv:OubinXCLIYxVfFRou1EJUJZExtzR5yZeR8Znt4n3uRY=,tag:AtsvjHzrKwMiB8oLlgP6JA==,type:comment]
    CDS_BASE_URL: ENC[AES256_GCM,data:s1raA+Rj73CUg5o1+4PAM1wAjk3uFG8=,iv:66k75AmAj8xu918a4KzwQHyvwiQvgAJhfXveaY0bVNU=,tag:RkZziVuEgSOz/xFdnlDPBA==,type:str]
    CDS_API_KEY: ENC[AES256_GCM,data:PvkFjz7F7xSFmpo5Qy3niMJTkrLpaV4rbgeH5d3SkuaM6QlhSp9LOLjhjHXaH6v9,iv:hGzpZ7EohhjN0edqBOkrGrNDNQxT/MtMQTek2gJM0V0=,tag:3oh5NZfBzqnRFeF76aIp9Q==,type:str]
    #ENC[AES256_GCM,data:l9Z/O8d7+SFvGloQYso8el1In375HA==,iv:lO/Z0eFr/w5U4Jyli0vWbE1fUxdnS/aQzP3GwS7A2q4=,tag:+5zMnq08rz8j9Y4rGC6OQQ==,type:comment]
    LOG_LEVEL: ENC[AES256_GCM,data:VQO7+w==,iv:Nc4VIMORIO7O0dWFjWbs78nY3vApBQxrMQ7CjNPB6+c=,tag:kayYGGKS0t+ZZ9Qfy+M8yA==,type:str]
    CLOUD_PROVIDER: ENC[AES256_GCM,data:5d2hhdI=,iv:jFaUDSkFz53ltkw+SkfJfpUdV+7kxp1M+NxO4/H+t7I=,tag:6fbEmWsc+gjym+xtUdpCuA==,type:str]
    #ENC[AES256_GCM,data:+TLcIuwmvQs=,iv:H1+qIlzOQ8PwKpmH6i+FtGaIF0LU9VAhOiHGkYS7zX0=,tag:9JhLKM/keAc6xvR44Ve9og==,type:comment]
    EV_CHARGING_UBC_BPP_ID: ENC[AES256_GCM,data:ivgtkTcAwdojgeonDHjiGb9GGVH61G7I,iv:/TTZpyUBJJF5sdnp+QzeJPsNy/urOHwxbz9EYHxOwjM=,tag:J5b1YbXnNG+hZw+HF6IfCw==,type:str]
    EV_CHARGING_UBC_UNIQUE_ID: ENC[AES256_GCM,data:xpI/5UlYSrHs9JQRCImXUiYiJ4AzeVcCjLFiNsAUNXddSLta7b0BrU+ZHNU0tJ1NpVORzwPK,iv:LFclPBCeotG5XvXZYwMl3EnTXsDIUuL/MKb79L9eRgs=,tag:wWx9QoqDETDKEOKtzHTexA==,type:str]
    #ENC[AES256_GCM,data:7uz2ug==,iv:gCTftuNhNbEnDZQLISEewdYahomecOH02EZfJXgkwag=,tag:iUmQXiDv3EPpQHk9aG05Rg==,type:comment]
    EV_CHARGING_UBC_BPP_CLIENT_HOST: ENC[AES256_GCM,data:UHuJOseUqzeFIvig1b4cYw2FAIDsIVxdYt6T,iv:BlZFn+7Tu1WyHPPc9ACVfYzKvpNtSmz9OcpoZBz5i9w=,tag:wBR4cQbkbhHxi8z+HjdUgg==,type:str]
    PRIVATE_KEY: ENC[AES256_GCM,data:ga/iY1g/VcvkUviQ5deAmec8xDKkspaI61SEYonLZli3py0dyUOG/AWHkjqm5l6nsbAA3ngDLYpv3VRtcu8M9WQLWLNQlfwI83hD2Qn2qjPSkE5wXkv2QQ==,iv:s8fKH8+Shqqzxrl8SGc6SHZxlGb39svNis9doTu7ABA=,tag:UrUJfD25mow5HH2KnIsgyQ==,type:str]
    INTERNAL_PAYMENT_LINK_HOST: ENC[AES256_GCM,data:+HPAsr3I8NCISdMnYSgFm57J/3ZRyHCjdw0Jai9h8xmQ1Q/ZLDKlUxVNMihY,iv:jJLzrMDmmt+ywnWD4EaPLclZJWhbA7rT0OndzzBVLX0=,tag:Vz7w4oWi1kzfvvWRH5U7ew==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pulse-energy/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-01-09T13:13:49Z"
          enc: CiQAHUiybhK6JsLp67a9lbO9ATqWaZOty0C6WsYeiamnFoPMY0USSQCT28oBJNHbKY2hyxvCurCMIfut5IsGTYeCa7gWCieVGSLhDZWV/XQhNP4DU4lb65xSUUjYoDCvYfi3RePMnh98Sn1Dh/INYb0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-09T13:13:50Z"
    mac: ENC[AES256_GCM,data:DUbb+Ld8p8rObO3ZJBQtHxmS/d7i3OCI9OQ98iBTmmmKqsUtAD8qCzJeRxIptpBq/xky/uqLev5fcoVVATK9g70+D/TxawX/QuUHtpGhzwGaBdaT9oJLe8G3NgbqiVxTyyBYqpoPC4LsAzDWG/MnCcOitKu4lwQq6axXWZmBUlY=,iv:lIrTT6VInU9orqD5diFqlRT/l4Fx6qHiiYkMgseQMOo=,tag:/YTDmCM5pzDSmLWnqN78aA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
