apiVersion: v1
kind: Secret
metadata:
    name: prod-pulse-ubc-ocpi-adaptor-secret
type: Opaque
stringData:
    NODE_ENV: ENC[AES256_GCM,data:wsR7vw==,iv:eip7YngU3nIhH0jbrSuWf1JarOw9yCRO/pKomzcGiIw=,tag:5FXC+yscdJz65iAceLiHLg==,type:str]
    REST_PORT: ENC[AES256_GCM,data:oKNtug==,iv:j8nK7IBiCEE5k+at0Ez7WuhhNtmIMBNLaFJqWj+vo5E=,tag:SlCZ3SKjPB1QcZggE5QuAw==,type:str]
    LOG_TIMESTAMP: ENC[AES256_GCM,data:T6UQRw==,iv:1wtKsmtkYKqva8E/FBLi7NsEwUVxAqRcS2x+C1DGnvo=,tag:Xrj+vVazSW3P13MZBJwyfg==,type:str]
    #ENC[AES256_GCM,data:ypSzhKTJjlbvVMz4nExNrG6eBUHnrw==,iv:DjVVb3491iLAGd2e/Zf8qSG9h7GBXIVcN7LwDHHGzJk=,tag:sGTq47FJzaz41WHXIueiKw==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:2xmy7vjc+MYBqSmRNpNiwsTEYMRms4QZx3JZxm98sv6DhIVfuf8JQU9f//8uFFca9eIVzw4Unp+wgYl8PnSpgDsY97Dk4leCTD1vaWD5wprdaMG9tHfhPnwU3kKx0EH1sD/lekVGTRMY0Oy8Xe/I78ZidfIEkK4cWH4cbQu0GxzeMP0TgFjLPXj3vobEQU5C0DQwi/pxydIbFd9HrgHFhXVVeSDvre7kU4hQW6r7GlZZtZZPjBbrnyvTzlxahY4uZqCOuciKgFoRVwD7TZaRlszTAQf68Tc=,iv:PYNb/tPJtimJX9m/7IY7DrTetAgSXc4aR8MlTFuuKSU=,tag:e5DtZXekF4yOtZ757S28zg==,type:str]
    #ENC[AES256_GCM,data:B1J8RZDqrCp27+24A8D2+bjDXA==,iv:XY9Yo+i+La5JmO+5r8dexvMSAWEjBvr9dCKOmeQgXxo=,tag:DJVP2VRkEvw5r/DhPz1fUA==,type:comment]
    OCPI_HOST: ENC[AES256_GCM,data:YFIH3K0JyQPYpwZ8QyOUm/5bzOOvm1DtOI8vgNd4w2m55FlWnPwLKpwmHZ3+,iv:0ndsvFOL1zY2TSrgMZcwbCH+dYn8waAXwqBTR6dCLoM=,tag:0KA1FgfxMYnr0oDZaz7heQ==,type:str]
    OCPI_VERSION: ENC[AES256_GCM,data:7fMmZU0=,iv:4MMc+YTlZsi4hATQEbcCiAEEsZvv8VjO/Q3+L6zUWIE=,tag:yiIsOI5YvUUlk2FLTVSDPA==,type:str]
    OCPI_PARTY_ID: ENC[AES256_GCM,data:Cg+p,iv:w6E0TZB9XCZjKU1LLVaoIJFH2CGwM2UyUu3cXyovskA=,tag:6/rAXXu3DLWAv8uxHn2+vQ==,type:str]
    OCPI_COUNTRY_CODE: ENC[AES256_GCM,data:86U=,iv:ckZJF9lZynEo9mkyUAtGOiY3tYZN11jZNRnOvY7iBv8=,tag:xRdt/U2jSbE/Tc4gI8Zg6Q==,type:str]
    #ENC[AES256_GCM,data:LVWcc1OgUKzOycfweymou6MXyNFL0mw5nSuQMtHTSegcLgl9x5iRyhPtPS13,iv:DAqd2AO6S6YqEsXVJaHQvUGYTTnml7/8feVDjQzYC2Y=,tag:NvSDGquVVqDnukktEQnDxA==,type:comment]
    CDS_BASE_URL: ENC[AES256_GCM,data:Pf0lbtvxwPQCN7NuVDqQ5qg1AU4mRtA=,iv:qrEURPO/6XyX/LYCSko2q+7fN4EIyt9fHqPiGEcdYzk=,tag:QGZhxB9jVAvHk5dSEDnpug==,type:str]
    CDS_API_KEY: ENC[AES256_GCM,data:/kW7/s0Ql7qLrdUIh+RGI6jXSecOz04kfu5xSZWnzIh2BozHb4PgYy8tFUbmIhzw,iv:sQNARI8KELwge8o4q91URojdgvIlqfBuXeduhPfLVNQ=,tag:Hbk871m4TUHU9bomps8QLg==,type:str]
    #ENC[AES256_GCM,data:wH8ZYw7HoEijrxoYNt3lWr4BxllQLQ==,iv:qm6+ICVYy2cSCWKS9iborOqYyY9lEWc3Aqw/EhSuzJo=,tag:fxJFxlg/MV1CCXDs7yI2CQ==,type:comment]
    LOG_LEVEL: ENC[AES256_GCM,data:/+Q82Q==,iv:UC5Uf4r6JZTD/UY9vt4vRDf46FeTf1+B1uDLojSvr90=,tag:ogAukVnTWtT9ggBs7dG2XA==,type:str]
    CLOUD_PROVIDER: ENC[AES256_GCM,data:U4PEuLU=,iv:/r4nerYA2s214m9rrq9t4mi2n4vHGSzAVt9RnwmOC3o=,tag:6hm4JmR69SoXdePOlM0xtw==,type:str]
    #ENC[AES256_GCM,data:dwL58uFwMmk=,iv:K8BpOg2ll1hxFwhVyzVBqDDHcAYkWwMWTJexq86mPAI=,tag:lf0CuKsOI2A5GZ8Go37sdw==,type:comment]
    EV_CHARGING_UBC_BPP_ID: ENC[AES256_GCM,data:CexsdusCRXe/xeTst6y9eQJEuJWRrTUK,iv:d48wF672Z79YzOrVvTWpm83lmkfDRxFi/3jkjjK0sMc=,tag:Bdu3Ow9M9j1Nr6FtTtDpRA==,type:str]
    EV_CHARGING_UBC_UNIQUE_ID: ENC[AES256_GCM,data:yAUyZCkppIYNDEcAvHyteLS+HypIv84yB9PYBGj9NyLdp7theq0ZYwuLLHUTN3aGffQBQblB,iv:8nj96C2xJjZ1lydEnFLvPAL/YqWBs14WDepdqcmzzSg=,tag:16sjKbkHa/nk4Y45CCiZ5A==,type:str]
    #ENC[AES256_GCM,data:6s5raA==,iv:z+1SiQpEuwjv6or3ZrraxvbgjPwFWdFX89I07wscFAQ=,tag:hzu4KCQpUGLJKbxhymXpQA==,type:comment]
    EV_CHARGING_UBC_BPP_CLIENT_HOST: ENC[AES256_GCM,data:jInpgJTeYek9CZAXyUK550YIKuj1pJAK3W1A,iv:JA6PXBqLPB8fvJAFWTPtKH2rWHpk7gACXlD5pddKnpc=,tag:3bFKii9X7k17bQSqb3hz3Q==,type:str]
    PRIVATE_KEY: ENC[AES256_GCM,data:JSvvPv/KYJS+/UCwcOdaui0k9cj9cWsNgT//P9mtRNuZ4aBgc3koTNwF6TQJqaQKsBnjkDdi1NpK2FEE8eBbbjBC6jnRkPwuta5MFX7sW5ZbRHfimE3syQ==,iv:TSdRM/VXpgXzn8ESFvnLCcuRSqEUWDMwY5Nq+4iwKvE=,tag:CTynt05DaVfN7np8745LvQ==,type:str]
    INTERNAL_PAYMENT_LINK_HOST: ENC[AES256_GCM,data:rSUciwC6/7cnyT7glLftdSQ4FIT6qxHUgzGl8Al+brhlTPdtuw1Q0WqZdAyj,iv:g48sNDFEodValD9XG1LTRl3YgE262j2INSPZwC7Z6sY=,tag:+r1HdlAmz/Sx0Mka2QAtGA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pulse-energy/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-01-20T17:54:47Z"
          enc: CiQAHUiybi77sbmB1YjFnoZYJYh2/iXGdc6jZSeV+py2/68Dk4ASSQCT28oBA1HaV//YEwjq8tCIgU7sh8pyr7Xx4rwSRYbIFleSppKs3IuL1eHcuCajsX4TkGhXT+UTwVToTSoSTIFzFzHcnvbDLLg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-20T17:54:47Z"
    mac: ENC[AES256_GCM,data:Jje7l5rpneDFj1RHtRUHud5nFF0XxQkoVlXaBeWjPe4SjKusnckCCiBDqOuW4RrMiHB52NreXKNTEMecDHvoIZNJ4g9WcdEhnyfVz237bAkFLQqIXkPN2fWgpfVBlyJtX/Bsy6hmYaIcFxG8Vg7unsuzs9pRnbWNxPe9tVAW52I=,iv:xl+l0qTGgUnSzWNWFX53PMiUWY6Oknb2qL66Z626Mak=,tag:V8hNFSwI6PlVA91+XqqBvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
