apiVersion: v1
kind: Secret
metadata:
    name: prod-pulse-ubc-ocpi-adaptor-secret
type: Opaque
stringData:
    NODE_ENV: ENC[AES256_GCM,data:9CeaRQ==,iv:HWkZD+N1MIaPs5LevX6V/PMFbvKwDlW10Uv0AUp6PYw=,tag:xNNCTBsBruSRnMhd2Jfz5A==,type:str]
    REST_PORT: ENC[AES256_GCM,data:TWeXmA==,iv:/WlY7DXYUsBYV6fySiD4ixLGNMWDuVQBuhBCQ3mzBp4=,tag:6eXPQjfD50T7HLJitrS3ig==,type:str]
    LOG_TIMESTAMP: ENC[AES256_GCM,data:5a5lyA==,iv:7kAQpPG9TZfy88P5P7UWHaCpx1quXKOOaa3sCOyE/C8=,tag:h8rX/wmGIQL+ISIL/sj3Qg==,type:str]
    #ENC[AES256_GCM,data:vuZvb2wCfCZ//daVYttnfgcUBHLLQA==,iv:HBQqFjNhDaVxr/VJoBv1TdZ/bLJkeypKjCFzJ2r2UgI=,tag:jWWEybIufclIqu/b0eCIQw==,type:comment]
    #ENC[AES256_GCM,data:SjUqv02wxAEVN7vA6AK/F1qa+sQoaaGEHtjmFYLweOPOkXNn2Rb2rlCTF9dRWHhqh5NqYiS5CrcN/2vCKt6H/aAp4XMh0JYvZnzKewWPPEk9jT21LTxAhtlJCzP2D9AR6rjsrUVr2tvV8icpwlXv0tbKcobBpQ/ZgnxkOvZGamIUPLGiO+D50/4TiczE9srfxzeuTdhf/b8wVKjNKRyX6nUxf0ZfmfMqUlx05yp6zcMjUBf0hRjt892e3XEHDuMhfyEVmdxb9vz2JmSk0uw8KoB9VKnHSAWDDqiZ3Q1GTOw8JP22k2Q2WDQ8Nf/07j+D,iv:Gmv28m99mjF6nNBJpPztRRAFWhgDSMX2syIbzE4bVnk=,tag:lh4qmdv5CzZ2PJrTtcyS1g==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:3PYzdZyez5yqr7o97dKmbMmY/tj1p3vVTyWKVRdPrTKcunWFKACr+IgeXNH93sW0Ahg0dD2ETX9mMeIscTyQwdxWuN9leRt8/Raby1n6El3QmIwt07iS/tAlxZW0LSONkGx3NlBVAl26vhgBJ7Y+D5M4JyjTfGd/OwhSjQmJu93gYBYWkPn1s9cD9UpxqIWzQ0pa+9CQXL86YNlEObk2EpBJjn6GsTvjHWeDpd7Ae7uDLChW51RrDKf9UpZ+OWStVSpBhHFMh0Bun7FMKJgIFX/XlpDh+Ck=,iv:+Pq/yoJ/fRhb3CRosVyVO8qD16Lg/DCoG9kgOIKX1e0=,tag:iYHZjwmZvnwZqVLynLooSA==,type:str]
    OCPI_HOST: ENC[AES256_GCM,data:Rtvd2dtANiUCAtWs4SVj5y4313GB9CDUClBGik7fNQ6t8PDfSjg0RYaN,iv:TWHZtRu603/hYuhsYINGFyEEflIJK4aL9zckiO5NzNg=,tag:Elp3Bwxw639x+nocdMq79A==,type:str]
    OCPI_VERSION: ENC[AES256_GCM,data:tuTRLoI=,iv:VipaCwrD3h6tuT7o+uE1seGHZz1iCFwhgZkQLtQb+GE=,tag:Zv5clXLwDM5bCC/wOQxBqg==,type:str]
    OCPI_PARTY_ID: ENC[AES256_GCM,data:VWk9,iv:i+fwzZOvXHMo9go0kkANnBFhXMJmrMO12K0ocED0stg=,tag:uvlgXFJSSrD7mB9Ju7bVGg==,type:str]
    OCPI_COUNTRY_CODE: ENC[AES256_GCM,data:hwA=,iv:ZrqqfgTwSS0BLeYNrlLZutzspRyTTwxUIrKyPjfSubA=,tag:0q1bQKFQmVnQm3tPHznzDg==,type:str]
    #ENC[AES256_GCM,data:vZzB7u+dpEFhTs6wYfpQV29wm9qDh/H0Y8v81why8ttLdFxvG2+y6zvXSN73,iv:npyD6YgVDOesk2qBCmbyXQD0ua45LA4DcLc22VIaDpE=,tag:1v/hOrj5KAGOfYM8M886RQ==,type:comment]
    CDS_BASE_URL: ENC[AES256_GCM,data:sl5QauLgHwpcd50Gvkl49EFLCgOZUbQ=,iv:SDp/RK7NWii1Hq2EHPMU8Zp9n2Vm5kGdwB9K4nv+kDY=,tag:IVJNFnlY9MbiZ9WOM+WA5Q==,type:str]
    CDS_API_KEY: ENC[AES256_GCM,data:QdoCir6dWV8jLELLFis8S5BRNhFY8XeFh/oGsyXCRhuc93Zm1F1XVRUtT9ljjH2l,iv:ooXfcudMKb+2PRRXPaL8Y+p+G1MYnkutRQauENq9v8c=,tag:Rg62AictIL0WCsbL9KQDmQ==,type:str]
    #ENC[AES256_GCM,data:4qgLeQ2yEy+h0MulBRA4hzS/Xe2Pyw==,iv:fzl0wZZXiJKltxntSZaInPsRTNRWGCzrpAMSw+e4CXc=,tag:LbigCmVxxxW64RRuuMGyvQ==,type:comment]
    LOG_LEVEL: ENC[AES256_GCM,data:SXL6QCk=,iv:tnJpQva005JRdcRlqGamdLl7pouQmP4lhMJiAa78cqA=,tag:txU/Ql3vuMG2m9ajAldabg==,type:str]
    CLOUD_PROVIDER: ENC[AES256_GCM,data:SEKh/CY=,iv:M0E0zC62lhwMqkznc9V9zEAt+ZytnEpD4mXARQnpsjQ=,tag:h3RaTy6Z1ekiiq5wwZH1zA==,type:str]
    #ENC[AES256_GCM,data:J/JW8at1lyU=,iv:p1hUctLp55yngzXmk6a6cRUIdjx/7SG9V/LEB73y2Xc=,tag:0MyVwBDLxUuHHDiU5JrcGg==,type:comment]
    EV_CHARGING_UBC_BPP_ID: ENC[AES256_GCM,data:YnedkqXdsHbsUhohGINnMxXU/PfZ,iv:oCOvMUfFMO3djH0KQytLBpK2ISitaaB/GbkDdci5YYk=,tag:oY5KOQ2d65oOzhL6GDQI0Q==,type:str]
    EV_CHARGING_UBC_UNIQUE_ID: ENC[AES256_GCM,data:ztclnAokoIDysBgwrXLia29Uy661+UhxP5HIakHvOSXyrXQMlSPK713dIbSxVuYRJh/SlXFS,iv:J5YgtkI5SHlUb4D2HUNNbXrOa1pN6mR5zPJKcIsjzto=,tag:Kvh8ed5mVZKNs2xvHhdvbw==,type:str]
    #ENC[AES256_GCM,data:Gv1KWQ==,iv:P1qw0SGJVnyvf7ZW6C+SVZjz1D4KupwyQ2pxB5z3sps=,tag:lqOy8IwqgI0tq1SWCGgGfg==,type:comment]
    EV_CHARGING_UBC_BPP_CLIENT_HOST: ENC[AES256_GCM,data:C1V1ZirTxlG7z1PX/fiFVWnpMZSmUFY0U6MhXGKXVAVO,iv:5L8raeSKvwr57FM1pgfHfOFGu6CU/U7jl4wKMJMABok=,tag:TI85ls6vFKXm7iRphObl6Q==,type:str]
    #ENC[AES256_GCM,data:WhYtB942vVKOo0ETmZjMSgdKOzSHgn+CORRxq9JkebI0vbGI7fKPI+DAQm6VfAewkH0MLmeWaIkUN+pk9o6A/E5EzrhVDMcpv+20hUV+UUMGCNVAhBpAjXq8VGdKFSmI4mmT8SAM,iv:gN+10zP8hqkbQngOwbC7SF8Pmc13JFeRNVbH1bbz/94=,tag:mmYzXzt6GvgrOq7as2kJbg==,type:comment]
    PRIVATE_KEY: ENC[AES256_GCM,data:EtfSaQi4LcoiUGk7k73OTh2SPsX7Y8mfAGtBpWC8Po8J7TxZ6A9QV0cdUU4=,iv:0om89GzXMV7BJ0UIUAZcm4Ie2EgqxZe2MLvmUrHoaKk=,tag:CBXdi6coYOnD5BU3h1UYxQ==,type:str]
    INTERNAL_PAYMENT_LINK_HOST: ENC[AES256_GCM,data:XuCG7dUUB4ti455pJiWVLan24zO4bozrpHvgieVE0WNuCLdZJ3K0vzwn,iv:k5Bl2c39O2vF9UJyZkIyxCkO2DfDtzzgRBy4tS7dc0w=,tag:5XFnQ3D4hsP3aY9Mw/IvOg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/pulse-energy/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-01-27T12:39:37Z"
          enc: CiQAHUiybrHHC82CNgmJBhEyiu1Y+9wKvCvPrtm0VFB1AVtIvxcSSQCT28oBPDg14Y/cZGlUTKQxYxxKRFtv5jTaTLIr2CQwi1CIhV+8MbliPqan4KQBZi+hjgHwi5zG9fKuc3hkZiQNQdk9Dw++ndk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-27T12:39:38Z"
    mac: ENC[AES256_GCM,data:m/TDESDxxboUSCaFgIDYabOekqEKg1IuY0W5/UwzLRJ1B2PgE7Fx/fmp5cuKgz4yhwMrzQxTF7K3S3Qpo3V73elazYJ7UagNSyXCyellulC43JPNfi/vTjbIMouKODWFaPoIMO9iGVvKYYPVIOyY3HEKColSThlngoBPj9qW1CU=,iv:JpsqtmyrTgjbnqETci7yVnE7AEuHcXuBnyVs9Fx8m9s=,tag:Ei/+leDTMsxhtEWqLsprXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
