apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pulse-ubc-ocpi-adaptor-hpa
  namespace: pulse-energy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pulse-ubc-ocpi-adaptor-wl
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
