apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pulse-energy

resources:
  - ../../../applications/pulse-ubc-ocpi-adaptor/
  - hpa.yaml

patches:
  - path: deployment-patch.yaml
