// 13.4.1
export enum OCPICommandResponseType {
    NOT_SUPPORTED = 'NOT_SUPPORTED',
    REJECTED = 'REJECTED',
    ACCEPTED = 'ACCEPTED',
    UNKNOWN_SESSION = 'UNKNOWN_SESSION',
}

// #OCPIv2.1.1
// 13.4.1
export enum OCPIv211CommandResponseType {
    NOT_SUPPORTED = 'NOT_SUPPORTED',
    REJECTED = 'REJECTED',
    ACCEPTED = 'ACCEPTED',
    TIMEOUT = 'TIMEOUT',
    UNKNOWN_SESSION = 'UNKNOWN_SESSION',
}

// 13.4.2
export enum OCPICommandResultType {
    ACCEPTED = 'ACCEPTED',
    CANCELED_RESERVATION = 'CANCELED_RESERVATION',
    EVSE_OCCUPIED = 'EVSE_OCCUPIED',
    EVSE_INOPERATIVE = 'EVSE_INOPERATIVE',
    FAILED = 'FAILED',
    NOT_SUPPORTED = 'NOT_SUPPORTED',
    REJECTED = 'REJECTED',
    TIMEOUT = 'TIMEOUT',
    UNKNOWN_RESERVATION = 'UNKNOWN_RESERVATION',
}

// 13.4.3
export enum OCPICommandType {
    CANCEL_RESERVATION = 'CANCEL_RESERVATION',
    RESERVE_NOW = 'RESERVE_NOW',
    START_SESSION = 'START_SESSION',
    STOP_SESSION = 'STOP_SESSION',
    UNLOCK_CONNECTOR = 'UNLOCK_CONNECTOR',
}

// #OCPIv2.1.1
// 13.4.3
export enum OCPIv211CommandType {
    RESERVE_NOW = 'RESERVE_NOW',
    START_SESSION = 'START_SESSION',
    STOP_SESSION = 'STOP_SESSION',
    UNLOCK_CONNECTOR = 'UNLOCK_CONNECTOR',
}
