/**
 * Razorpay Payment Gateway Types
 * Based on Razorpay API Documentation:
 * - https://razorpay.com/docs/payments/payment-gateway/s2s-integration/payment-methods/upi/
 * - https://razorpay.com/docs/payments/payment-gateway/s2s-integration/payment-methods/upi/intent/
 * - https://razorpay.com/docs/payments/payment-gateway/s2s-integration/payment-methods/upi/collect/
 * - https://razorpay.com/docs/api/orders/
 * - https://razorpay.com/docs/api/refunds/
 */

// ============ Enums ============

export enum RazorpayPaymentStatus {
    Created = 'created',
    Authorized = 'authorized',
    Captured = 'captured',
    Refunded = 'refunded',
    Failed = 'failed',
}

export enum RazorpayRefundStatus {
    Pending = 'pending',
    Processed = 'processed',
    Failed = 'failed',
}

export enum RazorpayOrderStatus {
    Created = 'created',
    Attempted = 'attempted',
    Paid = 'paid',
}

export enum RazorpayUPIFlow {
    Intent = 'intent',
    Collect = 'collect',
}

export enum RazorpayPaymentMethod {
    UPI = 'upi',
    Card = 'card',
    NetBanking = 'netbanking',
    Wallet = 'wallet',
    EMI = 'emi',
}

// ============ Webhook Event Types ============

export enum RazorpayWebhookEvent {
    OrderPaid = 'order.paid',
    PaymentAuthorized = 'payment.authorized',
    PaymentCaptured = 'payment.captured',
    PaymentFailed = 'payment.failed',
    RefundCreated = 'refund.created',
    RefundProcessed = 'refund.processed',
    RefundFailed = 'refund.failed',
}

// ============ Credentials ============

export interface RazorpayCredentials {
    /** Razorpay Key ID (provided by Razorpay) */
    KEY_ID: string;
    /** Razorpay Key Secret (provided by Razorpay) */
    KEY_SECRET: string;
    /** API Base URL (default: https://api.razorpay.com/v1) */
    API_URL?: string;
    /** Webhook Secret for verifying webhook signatures */
    WEBHOOK_SECRET?: string;

    /** Fee percentage (default: 0.2) */
    FEE_PERCENTAGE?: number;
}

// ============ Additional Info / Notes ============

export interface RazorpayNotes {
    [key: string]: string;
}

// ============ Create Order ============
// Reference: https://razorpay.com/docs/api/orders/

export interface RazorpayCreateOrderRequest {
    /** Amount in smallest currency unit (e.g., paise for INR). Min: 100 */
    amount: number;
    /** ISO currency code. Only INR is supported for UPI */
    currency: string;
    /** Receipt number for your internal reference (max 40 chars) */
    receipt?: string;
    /** Key-value pairs for additional info (max 15 pairs, 256 chars each) */
    notes?: RazorpayNotes;
    /** Partial payment settings (optional) */
    partial_payment?: boolean;
    /** Minimum first payment amount for partial payments */
    first_payment_min_amount?: number;
}

export interface RazorpayCreateOrderResponse {
    /** Unique order ID generated by Razorpay */
    id: string;
    /** Entity type - "order" */
    entity: string;
    /** Order amount in smallest currency unit */
    amount: number;
    /** Amount paid so far */
    amount_paid: number;
    /** Amount remaining to be paid */
    amount_due: number;
    /** Currency code */
    currency: string;
    /** Receipt number */
    receipt: string | null;
    /** Offer ID if applicable */
    offer_id: string | null;
    /** Order status: created, attempted, paid */
    status: RazorpayOrderStatus | string;
    /** Number of payment attempts */
    attempts: number;
    /** Additional notes */
    notes: RazorpayNotes | string[];
    /** Unix timestamp of creation */
    created_at: number;
}

// ============ Create UPI Payment ============
// Reference: https://razorpay.com/docs/payments/payment-gateway/s2s-integration/payment-methods/upi/

export interface RazorpayCreateUPIPaymentRequest {
    /** Amount in smallest currency unit (paise) */
    amount: number;
    /** Currency code (INR) */
    currency: string;
    /** Razorpay Order ID */
    order_id: string;
    /** Customer email */
    email?: string;
    /** Customer phone number */
    contact?: string;
    /** Payment method - "upi" */
    method: 'upi';
    /** Customer ID (required for saving VPA) */
    customer_id?: string;
    /** Whether to save VPA as token */
    save?: boolean;
    /** Client's IP address */
    ip?: string;
    /** Referer header value */
    referer?: string;
    /** User agent string */
    user_agent?: string;
    /** Payment description */
    description?: string;
    /** Additional notes */
    notes?: RazorpayNotes;
    /** UPI specific options */
    upi: {
        /** UPI flow type: intent or collect */
        flow: RazorpayUPIFlow | string;
        /** VPA/UPI ID (required for collect flow) */
        vpa?: string;
        /** Collect request expiry time in minutes (default: 5, max: 5760) */
        expiry_time?: number;
    };
    /** Callback URL for payment status */
    callback_url?: string;
    /** Fee amount in paise (for Customer Fee Bearer - CFB) */
    fee?: number;
}

export interface RazorpayCreateUPIPaymentResponse {
    /** Razorpay Payment ID */
    razorpay_payment_id: string;
    /** UPI Intent link (only for intent flow) */
    link?: string;
    /** Next actions to take */
    next?: Array<{
        action: string;
        url: string;
    }>;
}

// ============ Create Payment with Token ============
// For repeat transactions using saved VPA tokens

export interface RazorpayCreateTokenPaymentRequest {
    /** Amount in smallest currency unit (paise) */
    amount: number;
    /** Currency code (INR) */
    currency: string;
    /** Razorpay Order ID */
    order_id: string;
    /** Customer email */
    email: string;
    /** Customer phone number */
    contact: string;
    /** Payment method - "upi" */
    method: 'upi';
    /** Customer ID */
    customer_id: string;
    /** Saved VPA token */
    token: string;
    /** Client's IP address */
    ip?: string;
    /** Referer header value */
    referer?: string;
    /** User agent string */
    user_agent?: string;
    /** Payment description */
    description?: string;
    /** Additional notes */
    notes?: RazorpayNotes;
}

// ============ Validate VPA ============
// Reference: https://razorpay.com/docs/payments/payment-gateway/s2s-integration/payment-methods/upi/collect/

export interface RazorpayValidateVPARequest {
    /** VPA/UPI ID to validate */
    vpa: string;
}

export interface RazorpayValidateVPAResponse {
    /** The validated VPA */
    vpa: string;
    /** Whether VPA is valid */
    success: boolean;
    /** Customer name associated with VPA */
    customer_name: string;
}

// ============ Calculate Fees ============
// Reference: https://razorpay.com/docs/payments/payment-gateway/s2s-integration/payment-methods/upi/cfb-cc-upi/

export interface RazorpayCalculateFeesRequest {
    /** Amount in smallest currency unit */
    amount: number;
    /** Currency code */
    currency: string;
    /** Payment method */
    method: string;
    /** UPI details */
    upi?: {
        flow: string;
    };
    /** Customer contact */
    contact: string;
    /** Customer email */
    email: string;
    /** Payment description */
    description?: string;
    /** Payer account type (credit_card for CFB) */
    payer_account_type?: string;
}

export interface RazorpayCalculateFeesResponse {
    input: {
        amount: number;
        currency: string;
        method: string;
        fee: number;
        tax: number;
        payer_account_type?: string;
        upi?: {
            flow: string;
            type: string;
        };
    };
    display: {
        originalAmount: number;
        original_amount: number;
        fees: number;
        razorpay_fee: number;
        tax: number;
        amount: number;
        currency: string;
    };
}

// ============ Fetch Payment ============

export interface RazorpayPaymentResponse {
    /** Payment ID */
    id: string;
    /** Entity type - "payment" */
    entity: string;
    /** Payment amount in paise */
    amount: number;
    /** Currency code */
    currency: string;
    /** Payment status */
    status: RazorpayPaymentStatus | string;
    /** Order ID */
    order_id: string;
    /** Invoice ID if applicable */
    invoice_id: string | null;
    /** Whether payment is international */
    international: boolean;
    /** Payment method */
    method: string;
    /** Amount refunded */
    amount_refunded: number;
    /** Amount captured */
    amount_captured: number | null;
    /** Amount transferred */
    amount_transferred: number;
    /** Base amount */
    base_amount: number;
    /** Refund status */
    refund_status: string | null;
    /** Whether payment was captured */
    captured: boolean;
    /** Description */
    description: string;
    /** Card ID if card payment */
    card_id: string | null;
    /** Bank code */
    bank: string | null;
    /** Wallet type */
    wallet: string | null;
    /** VPA/UPI ID */
    vpa: string | null;
    /** Customer email */
    email: string;
    /** Customer contact */
    contact: string;
    /** Customer ID */
    customer_id: string | null;
    /** Additional notes */
    notes: RazorpayNotes | string[];
    /** Fee charged */
    fee: number | null;
    /** Tax on fee */
    tax: number | null;
    /** Error code if failed */
    error_code: string | null;
    /** Error description */
    error_description: string | null;
    /** Error source */
    error_source: string | null;
    /** Error step */
    error_step: string | null;
    /** Error reason */
    error_reason: string | null;
    /** Acquirer data */
    acquirer_data: {
        bank_transaction_id?: string;
        rrn?: string;
        upi_transaction_id?: string;
    } | null;
    /** Unix timestamp of creation */
    created_at: number;
    /** UPI details */
    upi?: {
        flow?: string;
        vpa?: string;
        payer_account_type?: string;
    };
    /** Payment provider */
    provider: string | null;
    /** Reward */
    reward: string | null;
}

// ============ Fetch Order Payments ============

export interface RazorpayOrderPaymentsResponse {
    entity: string;
    count: number;
    items: RazorpayPaymentResponse[];
}

// ============ Create Customer ============

export interface RazorpayCreateCustomerRequest {
    /** Customer name */
    name: string;
    /** Customer email */
    email?: string;
    /** Customer phone */
    contact?: string;
    /** Get existing customer if exists */
    fail_existing?: string;
    /** Additional notes */
    notes?: RazorpayNotes;
}

export interface RazorpayCustomerResponse {
    /** Customer ID */
    id: string;
    /** Entity type - "customer" */
    entity: string;
    /** Customer name */
    name: string;
    /** Customer email */
    email: string;
    /** Customer phone */
    contact: string;
    /** GSTIN */
    gstin: string | null;
    /** Unix timestamp of creation */
    created_at: number;
}

// ============ Fetch Customer Tokens ============

export interface RazorpayTokenResponse {
    /** Token ID */
    id: string;
    /** Entity type - "token" */
    entity: string;
    /** Token value */
    token: string;
    /** Bank for netbanking */
    bank: string | null;
    /** Wallet type */
    wallet: string | null;
    /** Payment method */
    method: string;
    /** VPA for UPI tokens */
    vpa?: {
        username: string;
        handle: string;
        name: string;
    };
    /** Card details for card tokens */
    card?: {
        name: string;
        network: string;
        type: string;
        last4: string;
    };
    /** Recurring info */
    recurring: boolean;
    /** Auth type */
    auth_type: string | null;
    /** Max payment amount */
    max_payment_amount: number | null;
    /** Token expiry */
    expired_at: number;
    /** Failure reason if applicable */
    dcc_enabled: boolean;
}

export interface RazorpayTokensResponse {
    entity: string;
    count: number;
    items: RazorpayTokenResponse[];
}

// ============ Refund ============
// Reference: https://razorpay.com/docs/api/refunds/

export interface RazorpayCreateRefundRequest {
    /** Refund amount in smallest currency unit (optional, full refund if not provided) */
    amount?: number;
    /** Speed of refund: normal or optimum */
    speed?: 'normal' | 'optimum';
    /** Additional notes */
    notes?: RazorpayNotes;
    /** Receipt for your reference */
    receipt?: string;
}

export interface RazorpayRefundResponse {
    /** Refund ID */
    id: string;
    /** Entity type - "refund" */
    entity: string;
    /** Refund amount */
    amount: number;
    /** Receipt */
    receipt: string | null;
    /** Currency */
    currency: string;
    /** Payment ID */
    payment_id: string;
    /** Additional notes */
    notes: RazorpayNotes | string[];
    /** Acquirer data */
    acquirer_data: {
        arn?: string;
        rrn?: string;
    } | null;
    /** Refund status */
    status: RazorpayRefundStatus | string;
    /** Speed requested */
    speed_requested: string;
    /** Speed processed */
    speed_processed: string;
    /** Unix timestamp of creation */
    created_at: number;
    /** Batch ID if applicable */
    batch_id: string | null;
}

// ============ Webhook Payload ============

export interface RazorpayWebhookPayload {
    /** Entity type */
    entity: string;
    /** Account ID */
    account_id: string;
    /** Event type (e.g., payment.authorized, payment.captured, payment.failed) */
    event: string;
    /** List of entity IDs related to this event */
    contains: string[];
    /** Event payload */
    payload: {
        payment?: {
            entity: RazorpayPaymentResponse;
        };
        order?: {
            entity: RazorpayCreateOrderResponse;
        };
        refund?: {
            entity: RazorpayRefundResponse;
        };
    };
    /** Unix timestamp of event creation */
    created_at: number;
}

// ============ Callback Payload ============

export interface RazorpayCallbackPayload {
    /** Razorpay Payment ID (on success) */
    razorpay_payment_id?: string;
    /** Razorpay Order ID (on success) */
    razorpay_order_id?: string;
    /** Razorpay Signature (on success) */
    razorpay_signature?: string;
    /** Error code (on failure) */
    error_code?: string;
    /** Error description (on failure) */
    error_description?: string;
    /** Error source (on failure) */
    error_source?: string;
    /** Error step (on failure) */
    error_step?: string;
    /** Error reason (on failure) */
    error_reason?: string;
    /** Metadata */
    metadata?: {
        order_id?: string;
        payment_id?: string;
    };
}

// ============ Payment Status Mapping ============

import { GenericPaymentTxnStatus } from '../Payment';

export const mapRazorpayStatusToGeneric = (status: string): GenericPaymentTxnStatus => {
    switch (status) {
        case RazorpayPaymentStatus.Captured:
            return GenericPaymentTxnStatus.Success;
        case RazorpayPaymentStatus.Failed:
            return GenericPaymentTxnStatus.Failed;
        case RazorpayPaymentStatus.Refunded:
            return GenericPaymentTxnStatus.Refunded;
        case RazorpayPaymentStatus.Created:
        case RazorpayPaymentStatus.Authorized:
        default:
            return GenericPaymentTxnStatus.Pending;
    }
};

export const mapRazorpayOrderStatusToGeneric = (status: string): GenericPaymentTxnStatus => {
    switch (status) {
        case RazorpayOrderStatus.Paid:
            return GenericPaymentTxnStatus.Success;
        case RazorpayOrderStatus.Created:
        case RazorpayOrderStatus.Attempted:
        default:
            return GenericPaymentTxnStatus.Pending;
    }
};

// ============ Service Props ============

export type RazorpayPaymentServiceProps = {
    callback_url?: string;
    device?: {
        ip?: string;
        user_agent?: string;
        referer?: string;
    };
};

// ============ Razorpay Object (for payment links) ============

export interface RazorpayObject {
    /** Payment URL or Intent URL */
    payment_url?: string;
    /** Intent link for UPI intent flow */
    intent_link?: string;
    /** Razorpay Order ID */
    order_id: string;
    /** Razorpay Payment ID (after payment creation) */
    payment_id?: string;
    /** Authorization reference */
    authorization_reference?: string;
}

// ============ Create Order Response Type ============

export interface CreateOrderWithRazorpayResponse {
    success: boolean;
    razorpayOrder?: RazorpayCreateOrderResponse;
    razorpayObject?: RazorpayObject;
    error?: string;
    error_details?: any;
}

// ============ Create UPI Payment Response Type ============

export interface CreateUPIPaymentWithRazorpayResponse {
    success: boolean;
    payment?: RazorpayCreateUPIPaymentResponse;
    razorpayObject?: RazorpayObject;
    error?: string;
    error_details?: any;
}

// ============ Error Response ============

export interface RazorpayErrorResponse {
    error: {
        code: string;
        description: string;
        source: string;
        step: string;
        reason: string;
        metadata?: {
            order_id?: string;
            payment_id?: string;
        };
        field?: string;
    };
}
