import { NextFunction, Request, Response, Router } from 'express';
import { randomUUID } from 'crypto';
import { OCPIPartnerCredentials } from '@prisma/client';
import { HttpResponse } from '../../types/responses';
import { logger } from '../../services/logger.service';
import { AppError } from '../../utils/errors';
import OCPIv221LocationsModuleOutgoingRequestService from '../../ocpi/modules/v2.2.1/emsp/locations/OCPIv221LocationsModuleOutgoingRequestService';
import OCPIv221TariffsModuleOutgoingRequestService from '../../ocpi/modules/v2.2.1/emsp/tariffs/OCPIv221TariffsModuleOutgoingRequestService';
import { databaseService } from '../../services/database.service';

const router = Router();

type AnyHttpResponse = HttpResponse<any, Record<string, string>>;

interface OCPIAuthedRequest extends Request {
    ocpiPartnerCredentials?: OCPIPartnerCredentials;
}

async function handleRequest(
    req: Request,
    res: Response,
    next: NextFunction,
    controller: (req: Request) => Promise<AnyHttpResponse>,
) {
    try {
        const response = await controller(req);
        
        // Set headers BEFORE sending the response
        if (response.headers) {
            Object.entries(response.headers).forEach(([key, value]) => {
                res.setHeader(key, value);
            });
        }
        
        // Send the response after headers are set
        res.status(response.httpStatus || 200).json(response.payload);
    }
    catch (error) {
        next(error);
    }
}

// Optional: simple auth/middleware hook if needed later
const ocpiApiAuth = async (req: Request, res: Response, next: NextFunction) => {
    // Generate request/correlation IDs if missing (case-insensitive check)
    const correlationId = req.headers['x-correlation-id'] as string || req.headers['X-Correlation-Id'] as string;
    const requestId = req.headers['x-request-id'] as string || req.headers['X-Request-Id'] as string;

    let generatedCorrelationId = false;
    let generatedRequestId = false;

    // Generate correlation ID if missing
    if (!correlationId) {
        const newCorrelationId = randomUUID();
        req.headers['x-correlation-id'] = newCorrelationId;
        req.headers['X-Correlation-Id'] = newCorrelationId;
        generatedCorrelationId = true;
        logger.info('Generated correlation ID for incoming request (UBC Adaptor)', {
            correlationId: newCorrelationId,
            path: req.path,
            method: req.method,
            data: {
                message: 'Correlation ID was missing and generated by UBC Adaptor',
                correlationId: newCorrelationId,
            },
        });
    }

    // Generate request ID if missing
    if (!requestId) {
        const newRequestId = randomUUID();
        req.headers['x-request-id'] = newRequestId;
        req.headers['X-Request-Id'] = newRequestId;
        generatedRequestId = true;
        logger.info('Generated request ID for incoming request (UBC Adaptor)', {
            requestId: newRequestId,
            path: req.path,
            method: req.method,
            data: {
                message: 'Request ID was missing and generated by UBC Adaptor',
                requestId: newRequestId,
            },
        });
    }

    // Log if any IDs were generated
    if (generatedCorrelationId || generatedRequestId) {
        const finalCorrelationId = req.headers['x-correlation-id'] as string;
        const finalRequestId = req.headers['x-request-id'] as string;
        logger.info('Request IDs status for incoming request', {
            correlationId: finalCorrelationId,
            requestId: finalRequestId,
            path: req.path,
            method: req.method,
            data: {
                message: 'Request IDs generated by UBC Adaptor',
                correlationIdGenerated: generatedCorrelationId,
                requestIdGenerated: generatedRequestId,
                correlationId: finalCorrelationId,
                requestId: finalRequestId,
            },
        });
    }

    // Get final IDs for logging
    const finalCorrelationId = req.headers['x-correlation-id'] as string;
    const finalRequestId = req.headers['x-request-id'] as string;

    // Log incoming request with full details
    const requestUrl = (req as any).originalUrl || req.url;
    const requestIp = req.ip || req.socket.remoteAddress || 'unknown';
    
    // Mask sensitive headers
    const safeHeaders = { ...req.headers };
    if (safeHeaders.authorization) {
        safeHeaders.authorization = 'Token ***';
    }

    logger.info('Incoming OCPI API Request (Internal)', {
        correlationId: finalCorrelationId,
        requestId: finalRequestId,
        path: req.path,
        method: req.method,
        url: requestUrl,
        ip: requestIp,
        timestamp: new Date().toISOString(),
        data: {
            method: req.method,
            url: requestUrl,
            path: req.path,
            query: req.query,
            headers: safeHeaders,
            body: req.body,
            correlationId: finalCorrelationId,
            requestId: finalRequestId,
            ip: requestIp,
            timestamp: new Date().toISOString(),
        },
    });

    // Add authentication/authorization here if desired
    const cpoAuthToken = req.headers.authorization?.substring('Token '.length);
    if (!cpoAuthToken) {
        res.status(401).json({
            status_code: 2001,
            status_message: 'Unauthorized',
            timestamp: new Date().toISOString(),
        });
        return;
    }

    const partnerCredentials = await databaseService.prisma.oCPIPartnerCredentials.findFirst({
        where: { cpo_auth_token: cpoAuthToken },
        include: { partner: true },
    });

    if (!partnerCredentials) {
        res.status(401).json({
            status_code: 2001,
            status_message: 'Unauthorized',
        });
        return;
    }

    (req as OCPIAuthedRequest).ocpiPartnerCredentials = partnerCredentials;

    next();
};
// Trigger a GET Locations towards CPO, store results in DB, and return OCPI payload
router.get(
    '/locations',
    ocpiApiAuth,
    async (req: Request, res: Response, next: NextFunction) =>
        handleRequest(
            req,
            res,
            next,
            (innerReq: Request) =>
                OCPIv221LocationsModuleOutgoingRequestService.sendGetLocations(
                    innerReq,
                    (req as OCPIAuthedRequest).ocpiPartnerCredentials?.cpo_auth_token ?? undefined,
                    (req as OCPIAuthedRequest).ocpiPartnerCredentials?.partner_id,
                ),
        ),
);

// Get a single location from DB; if missing, fetch from CPO, store, then return
router.get(
    '/locations/:location_id',
    ocpiApiAuth,
    async (req: Request, res: Response, next: NextFunction) =>
        handleRequest(
            req,
            res,
            next,
            (innerReq: Request) =>
                OCPIv221LocationsModuleOutgoingRequestService.sendGetLocation(
                    innerReq,
                    (req as OCPIAuthedRequest).ocpiPartnerCredentials?.cpo_auth_token ?? undefined,
                    (req as OCPIAuthedRequest).ocpiPartnerCredentials?.partner_id,
                ),
        ),
);


// Trigger a GET Tariffs towards CPO, store results in DB, and return OCPI payload (outgoing)
router.post(
    '/tariffs/fetch',
    ocpiApiAuth,
    async (req: Request, res: Response, next: NextFunction) =>
        handleRequest(
            req,
            res,
            next,
            (innerReq: Request) =>
                OCPIv221TariffsModuleOutgoingRequestService.sendGetTariffs(
                    innerReq,
                    (req as OCPIAuthedRequest).ocpiPartnerCredentials?.cpo_auth_token ?? undefined,
                    (req as OCPIAuthedRequest).ocpiPartnerCredentials?.partner_id,
                ),
        ),
);

// Get a single tariff from DB; if missing, fetch from CPO, store, then return (outgoing)
router.post(
    '/tariffs/:tariff_id/fetch',
    ocpiApiAuth,
    async (req: Request, res: Response, next: NextFunction) =>
        handleRequest(
            req,
            res,
            next,
            (innerReq: Request) =>
                OCPIv221TariffsModuleOutgoingRequestService.sendGetTariff(
                    innerReq,
                    (req as OCPIAuthedRequest).ocpiPartnerCredentials?.cpo_auth_token ?? undefined,
                    (req as OCPIAuthedRequest).ocpiPartnerCredentials?.partner_id,
                ),
        ),
);

// Error handling for this router
// eslint-disable-next-line @typescript-eslint/no-unused-vars
router.use((error: Error, req: Request, res: Response, _next: NextFunction): void => {
    logger.error('OCPI API (internal) error', error, {
        path: req.path,
        method: req.method,
    });

    if (error instanceof AppError) {
        res.status(error.statusCode).json({
            success: false,
            error: error.message,
        });
        return;
    }

    res.status(500).json({
        success: false,
        error: 'Internal server error',
    });
});

export default router;


